// AUTO-GENERAT — traduceri DE/RU/PL/NL pentru aditivi (E-uri).
// Se imbina automat in fisierul principal (vezi merge-ul de la finalul acelui fisier).
// Pentru a edita o limba existenta (ro/en/fr/it/es) modifica fisierul principal.
export const additivesExtra: Record<string, { name: any; use: any; desc: any }> = {
  "e100": {
    name: { de: "Kurkumin", ru: "Куркумин", pl: "Kurkumina", nl: "Curcumine" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Natürlicher gelber Farbstoff aus Kurkuma. In der EU zugelassen; die EFSA stuft ihn als sicher ein, ohne strenge Höchstdosis. Auch in den USA, Asien und weltweit erlaubt. Keine bekannten Risiken bei üblichen Mengen.", ru: "Натуральный жёлтый краситель из куркумы. Разрешён в ЕС; EFSA считает его безопасным, без строгой максимальной дозы. Также разрешён в США, Азии и по всему миру. Никаких известных рисков при обычном употреблении.", pl: "Naturalny żółty barwnik z kurkumy. Dopuszczony w UE; EFSA uznaje go za bezpieczny, bez ścisłej dawki maksymalnej. Dozwolony także w USA, Azji i na całym świecie. Brak znanych zagrożeń przy zwykłych ilościach.", nl: "Natuurlijke gele kleurstof uit kurkuma. Toegelaten in de EU; de EFSA beschouwt het als veilig, zonder strikte maximumdosis. Ook toegestaan in de VS, Azië en wereldwijd. Geen bekende risico's bij normale hoeveelheden." },
  },
  "e101": {
    name: { de: "Riboflavin (B2)", ru: "Рибофлавин (B2)", pl: "Ryboflawina (B2)", nl: "Riboflavine (B2)" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Vitamin B2, auch als gelber Farbstoff verwendet. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Ein essenzieller Nährstoff, völlig sicher.", ru: "Витамин B2, также используется как жёлтый краситель. Разрешён в ЕС и признан безопасным EFSA; разрешён во всём мире. Незаменимый питательный элемент, полностью безопасен.", pl: "Witamina B2, stosowana również jako żółty barwnik. Dopuszczona w UE i uznana za bezpieczną przez EFSA; dozwolona na całym świecie. Niezbędny składnik odżywczy, całkowicie bezpieczny.", nl: "Vitamine B2, ook gebruikt als gele kleurstof. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Een essentiële voedingsstof, volledig veilig." },
  },
  "e102": {
    name: { de: "Tartrazin", ru: "Тартразин", pl: "Tartrazyna", nl: "Tartrazine" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher gelber Farbstoff. Einer der \"Southampton-Sechs\": In der EU schreibt die Verordnung 1333/2008 vor, dass Produkte, die ihn enthalten, den Warnhinweis \"kann die Aktivität und Aufmerksamkeit von Kindern beeinträchtigen\" tragen müssen (seit 2010). In den USA erlaubt (FD&C Yellow 5). Kann allergische Reaktionen auslösen. Vorsicht, besonders bei Kindern.", ru: "Искусственный жёлтый краситель. Один из \"саутгемптонской шестёрки\": в ЕС Регламент 1333/2008 обязывает наносить на содержащие его продукты предупреждение \"может оказывать негативное влияние на активность и внимание детей\" (с 2010 года). Разрешён в США (FD&C Yellow 5). Может вызывать аллергические реакции. Осторожность, особенно у детей.", pl: "Sztuczny żółty barwnik. Jeden z \"szóstki z Southampton\": w UE rozporządzenie 1333/2008 wymaga, aby produkty go zawierające nosiły ostrzeżenie \"może mieć szkodliwy wpływ na aktywność i skupienie uwagi u dzieci\" (od 2010 roku). Dozwolony w USA (FD&C Yellow 5). Może wywoływać reakcje alergiczne. Ostrożność, zwłaszcza u dzieci.", nl: "Kunstmatige gele kleurstof. Een van de \"Southampton Six\": in de EU verplicht Verordening 1333/2008 producten die het bevatten de waarschuwing \"kan de activiteit en oplettendheid van kinderen nadelig beïnvloeden\" te dragen (sinds 2010). Toegestaan in de VS (FD&C Yellow 5). Kan allergische reacties veroorzaken. Voorzichtigheid, vooral bij kinderen." },
  },
  "e104": {
    name: { de: "Chinolingelb", ru: "Хинолиновый жёлтый", pl: "Żółcień chinolinowa", nl: "Chinolinegeel" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher gelber Farbstoff, einer der \"Southampton-Sechs\". In der EU ist der verpflichtende Warnhinweis zur Aufmerksamkeit von Kindern erforderlich (Verordnung 1333/2008), und die EFSA hat die zulässige Tagesdosis gesenkt. In den USA für Lebensmittel verboten. Vorsicht.", ru: "Искусственный жёлтый краситель, один из \"саутгемптонской шестёрки\". В ЕС требуется обязательное предупреждение о влиянии на внимание детей (Регл. 1333/2008), а EFSA снизила допустимую суточную дозу. Запрещён в пищевых продуктах в США. Осторожность.", pl: "Sztuczny żółty barwnik, jeden z \"szóstki z Southampton\". W UE wymaga obowiązkowego ostrzeżenia dotyczącego skupienia uwagi u dzieci (Rozp. 1333/2008), a EFSA obniżyła dopuszczalne dzienne spożycie. Zakazany w żywności w USA. Ostrożność.", nl: "Kunstmatige gele kleurstof, een van de \"Southampton Six\". In de EU is de verplichte waarschuwing over de oplettendheid van kinderen vereist (Verord. 1333/2008), en de EFSA heeft de aanvaardbare dagelijkse inname verlaagd. Verboden voor voedsel in de VS. Voorzichtigheid." },
  },
  "e110": {
    name: { de: "Gelborange S (Sunset Yellow)", ru: "Жёлтый \"солнечный закат\" (Sunset Yellow)", pl: "Żółcień pomarańczowa (Sunset Yellow)", nl: "Zonsondergeel (Sunset Yellow)" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher gelb-oranger Farbstoff, einer der \"Southampton-Sechs\". In der EU ist der verpflichtende Warnhinweis zur Aufmerksamkeit von Kindern erforderlich (Verordnung 1333/2008), und die EFSA hat die Tagesdosis gesenkt. In den USA erlaubt (FD&C Yellow 6). Kann Allergien auslösen. Vorsicht.", ru: "Искусственный жёлто-оранжевый краситель, один из \"саутгемптонской шестёрки\". В ЕС требуется обязательное предупреждение о влиянии на внимание детей (Регл. 1333/2008), а EFSA снизила суточную дозу. Разрешён в США (FD&C Yellow 6). Может вызывать аллергию. Осторожность.", pl: "Sztuczny żółto-pomarańczowy barwnik, jeden z \"szóstki z Southampton\". W UE wymaga obowiązkowego ostrzeżenia dotyczącego skupienia uwagi u dzieci (Rozp. 1333/2008), a EFSA obniżyła dzienne spożycie. Dozwolony w USA (FD&C Yellow 6). Może powodować alergie. Ostrożność.", nl: "Kunstmatige geeloranje kleurstof, een van de \"Southampton Six\". In de EU is de verplichte waarschuwing over de oplettendheid van kinderen vereist (Verord. 1333/2008), en de EFSA heeft de dagelijkse inname verlaagd. Toegestaan in de VS (FD&C Yellow 6). Kan allergieën veroorzaken. Voorzichtigheid." },
  },
  "e120": {
    name: { de: "Karminsäure (Cochenille)", ru: "Карминовая кислота (кошениль)", pl: "Kwas karminowy (koszenila)", nl: "Karmijnzuur (cochenille)" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Roter Farbstoff aus Cochenille-Insekten. In der EU zugelassen und von der EFSA als sicher eingestuft; auch in den USA erlaubt. Kann bei empfindlichen Personen allergische Reaktionen auslösen. Nicht vegan.", ru: "Красный краситель из насекомых (кошениль). Разрешён в ЕС и признан безопасным EFSA; также разрешён в США. Может вызывать аллергические реакции у чувствительных людей. Не подходит для веганов.", pl: "Czerwony barwnik z owadów (koszenila). Dopuszczony w UE i uznany za bezpieczny przez EFSA; dozwolony także w USA. Może wywoływać reakcje alergiczne u osób wrażliwych. Nieodpowiedni dla wegan.", nl: "Rode kleurstof uit cochenille-insecten. Toegelaten in de EU en door de EFSA als veilig beschouwd; ook toegestaan in de VS. Kan allergische reacties veroorzaken bij gevoelige personen. Niet veganistisch." },
  },
  "e122": {
    name: { de: "Azorubin (Carmoisin)", ru: "Азорубин (кармуазин)", pl: "Azorubina (karmoizyna)", nl: "Azorubine (carmoisine)" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher roter Farbstoff, einer der \"Southampton-Sechs\". In der EU ist der verpflichtende Warnhinweis zur Aufmerksamkeit von Kindern erforderlich (Verordnung 1333/2008). In den USA, Japan und Norwegen verboten. Vorsicht.", ru: "Искусственный красный краситель, один из \"саутгемптонской шестёрки\". В ЕС требуется обязательное предупреждение о влиянии на внимание детей (Регл. 1333/2008). Запрещён в США, Японии и Норвегии. Осторожность.", pl: "Sztuczny czerwony barwnik, jeden z \"szóstki z Southampton\". W UE wymaga obowiązkowego ostrzeżenia dotyczącego skupienia uwagi u dzieci (Rozp. 1333/2008). Zakazany w USA, Japonii i Norwegii. Ostrożność.", nl: "Kunstmatige rode kleurstof, een van de \"Southampton Six\". In de EU is de verplichte waarschuwing over de oplettendheid van kinderen vereist (Verord. 1333/2008). Verboden in de VS, Japan en Noorwegen. Voorzichtigheid." },
  },
  "e124": {
    name: { de: "Cochenillerot A (Ponceau 4R)", ru: "Понсо 4R (красный кошенилевый A)", pl: "Pąsowa 4R (czerwień koszenilowa A)", nl: "Ponceau 4R (cochenillerood A)" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher roter Farbstoff, einer der \"Southampton-Sechs\". In der EU ist der verpflichtende Warnhinweis zur Aufmerksamkeit von Kindern erforderlich (Verordnung 1333/2008), und die EFSA hat die Tagesdosis gesenkt. In den USA und Norwegen verboten. Vorsicht.", ru: "Искусственный красный краситель, один из \"саутгемптонской шестёрки\". В ЕС требуется обязательное предупреждение о влиянии на внимание детей (Регл. 1333/2008), а EFSA снизила суточную дозу. Запрещён в США и Норвегии. Осторожность.", pl: "Sztuczny czerwony barwnik, jeden z \"szóstki z Southampton\". W UE wymaga obowiązkowego ostrzeżenia dotyczącego skupienia uwagi u dzieci (Rozp. 1333/2008), a EFSA obniżyła dzienne spożycie. Zakazany w USA i Norwegii. Ostrożność.", nl: "Kunstmatige rode kleurstof, een van de \"Southampton Six\". In de EU is de verplichte waarschuwing over de oplettendheid van kinderen vereist (Verord. 1333/2008), en de EFSA heeft de dagelijkse inname verlaagd. Verboden in de VS en Noorwegen. Voorzichtigheid." },
  },
  "e129": {
    name: { de: "Allurarot AC", ru: "Красный очаровательный AC (Allura Red AC)", pl: "Czerwień Allura AC", nl: "Allurarood AC" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher roter Farbstoff, einer der \"Southampton-Sechs\", häufig in Süßigkeiten und Getränken. In der EU ist der verpflichtende Warnhinweis zur Aufmerksamkeit von Kindern erforderlich (Verordnung 1333/2008). In den USA erlaubt (FD&C Red 40), wo einige Bundesstaaten ebenfalls Warnhinweise verlangen. Vorsicht.", ru: "Искусственный красный краситель, один из \"саутгемптонской шестёрки\", часто встречается в сладостях и напитках. В ЕС требуется обязательное предупреждение о влиянии на внимание детей (Регл. 1333/2008). Разрешён в США (FD&C Red 40), где некоторые штаты также требуют предупреждений. Осторожность.", pl: "Sztuczny czerwony barwnik, jeden z \"szóstki z Southampton\", częsty w słodyczach i napojach. W UE wymaga obowiązkowego ostrzeżenia dotyczącego skupienia uwagi u dzieci (Rozp. 1333/2008). Dozwolony w USA (FD&C Red 40), gdzie niektóre stany również wymagają ostrzeżeń. Ostrożność.", nl: "Kunstmatige rode kleurstof, een van de \"Southampton Six\", veel voorkomend in snoep en dranken. In de EU is de verplichte waarschuwing over de oplettendheid van kinderen vereist (Verord. 1333/2008). Toegestaan in de VS (FD&C Red 40), waar sommige staten ook waarschuwingen vereisen. Voorzichtigheid." },
  },
  "e131": {
    name: { de: "Patentblau V", ru: "Синий патентованный V", pl: "Błękit patentowy V", nl: "Patentblauw V" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher blauer Farbstoff. In der EU mit Grenzwerten zugelassen (Verordnung 1333/2008); die EFSA hat eine Tagesdosis festgelegt. In den USA, Australien und Norwegen verboten. Kann seltene allergische Reaktionen auslösen. Mäßigung.", ru: "Искусственный синий краситель. Разрешён в ЕС с ограничениями (Регл. 1333/2008); EFSA установила суточную дозу. Запрещён в США, Австралии и Норвегии. Может вызывать редкие аллергические реакции. Умеренность.", pl: "Sztuczny niebieski barwnik. Dopuszczony w UE z ograniczeniami (Rozp. 1333/2008); EFSA ustaliła dzienne spożycie. Zakazany w USA, Australii i Norwegii. Może powodować rzadkie reakcje alergiczne. Umiarkowanie.", nl: "Kunstmatige blauwe kleurstof. Toegelaten in de EU met limieten (Verord. 1333/2008); de EFSA heeft een dagelijkse inname vastgesteld. Verboden in de VS, Australië en Noorwegen. Kan zeldzame allergische reacties veroorzaken. Matiging." },
  },
  "e132": {
    name: { de: "Indigotin (Indigokarmin)", ru: "Индиготин (индигокармин)", pl: "Indygotyna (karmin indygo)", nl: "Indigotine (indigokarmijn)" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher blauer Farbstoff. In der EU zugelassen und von der EFSA innerhalb der festgelegten Grenzwerte als sicher eingestuft; auch in den USA erlaubt (FD&C Blue 2). Mögliche allergische Reaktionen bei empfindlichen Personen. Mäßigung.", ru: "Искусственный синий краситель. Разрешён в ЕС и признан безопасным EFSA в установленных пределах; также разрешён в США (FD&C Blue 2). Возможны аллергические реакции у чувствительных людей. Умеренность.", pl: "Sztuczny niebieski barwnik. Dopuszczony w UE i uznany za bezpieczny przez EFSA w ustalonych granicach; dozwolony także w USA (FD&C Blue 2). Możliwe reakcje alergiczne u osób wrażliwych. Umiarkowanie.", nl: "Kunstmatige blauwe kleurstof. Toegelaten in de EU en door de EFSA binnen de vastgestelde limieten als veilig beschouwd; ook toegestaan in de VS (FD&C Blue 2). Mogelijke allergische reacties bij gevoelige personen. Matiging." },
  },
  "e133": {
    name: { de: "Brillantblau FCF", ru: "Синий блестящий FCF", pl: "Błękit brylantowy FCF", nl: "Briljantblauw FCF" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Künstlicher blauer Farbstoff. In der EU zugelassen und von der EFSA als relativ sicher eingestuft; auch in den USA erlaubt (FD&C Blue 1). Seltene allergische Reaktionen sind möglich. Mäßigung.", ru: "Искусственный синий краситель. Разрешён в ЕС и признан EFSA относительно безопасным; также разрешён в США (FD&C Blue 1). Возможны редкие аллергические реакции. Умеренность.", pl: "Sztuczny niebieski barwnik. Dopuszczony w UE i uznany przez EFSA za stosunkowo bezpieczny; dozwolony także w USA (FD&C Blue 1). Możliwe rzadkie reakcje alergiczne. Umiarkowanie.", nl: "Kunstmatige blauwe kleurstof. Toegelaten in de EU en door de EFSA als relatief veilig beschouwd; ook toegestaan in de VS (FD&C Blue 1). Zeldzame allergische reacties zijn mogelijk. Matiging." },
  },
  "e140": {
    name: { de: "Chlorophylle", ru: "Хлорофиллы", pl: "Chlorofile", nl: "Chlorofyl" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Natürlicher grüner Farbstoff aus Pflanzen. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Keine bekannten Risiken.", ru: "Натуральный зелёный краситель из растений. Разрешён в ЕС и признан безопасным EFSA; разрешён во всём мире. Никаких известных рисков.", pl: "Naturalny zielony barwnik z roślin. Dopuszczony w UE i uznany za bezpieczny przez EFSA; dozwolony na całym świecie. Brak znanych zagrożeń.", nl: "Natuurlijke groene kleurstof uit planten. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Geen bekende risico's." },
  },
  "e150a": {
    name: { de: "Einfaches Zuckerkulör", ru: "Карамель обыкновенная", pl: "Karmel zwykły", nl: "Gewone karamel" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Brauner Farbstoff aus erhitztem Zucker. Die einfachste Form, in der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Maßvoller Verzehr, da es in vielen verarbeiteten Lebensmitteln vorkommt.", ru: "Коричневый краситель из нагретого сахара. Самая простая форма, разрешённая в ЕС и признанная безопасной EFSA; разрешена во всём мире. Умеренное употребление, так как встречается во многих обработанных продуктах.", pl: "Brązowy barwnik z podgrzewanego cukru. Najprostsza postać, dopuszczona w UE i uznana za bezpieczną przez EFSA; dozwolona na całym świecie. Umiarkowane spożycie, ponieważ występuje w wielu produktach przetworzonych.", nl: "Bruine kleurstof uit verhitte suiker. De eenvoudigste vorm, toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Matig gebruik omdat het in veel bewerkte voedingsmiddelen voorkomt." },
  },
  "e150d": {
    name: { de: "Ammonsulfit-Zuckerkulör", ru: "Сахарный колер IV (аммиачно-сульфитный)", pl: "Karmel amoniakalno-siarczynowy", nl: "Sulfietammoniakkaramel" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Brauner Farbstoff in Cola-Getränken und Balsamico-Essig. In der EU zugelassen, doch die EFSA hat Produktionsgrenzwerte festgelegt, um 4-MEI zu verringern, eine möglicherweise krebserregende Substanz. In den USA sind in bestimmten Fällen Warnhinweise erforderlich, wenn der 4-MEI-Gehalt einen Schwellenwert überschreitet. Maßvoller Verzehr empfohlen, besonders bei Kindern.", ru: "Коричневый краситель в напитках типа колы и бальзамическом уксусе. Разрешён в ЕС, но EFSA установила производственные ограничения для снижения содержания 4-MEI — возможно канцерогенного вещества. В США в некоторых случаях требуются предупреждения, когда уровень 4-MEI превышает порог. Рекомендуется умеренное потребление, особенно детям.", pl: "Brązowy barwnik w napojach typu cola i occie balsamicznym. Dozwolony w UE, ale EFSA ustaliła limity produkcyjne, aby ograniczyć 4-MEI — substancję potencjalnie rakotwórczą. W USA w niektórych przypadkach wymagane są ostrzeżenia, gdy poziom 4-MEI przekracza próg. Zalecane umiarkowane spożycie, zwłaszcza u dzieci.", nl: "Bruine kleurstof in coladranken en balsamicoazijn. Toegelaten in de EU, maar de EFSA heeft productiegrenzen vastgesteld om 4-MEI te beperken, een mogelijk kankerverwekkende stof. In de VS zijn in bepaalde gevallen waarschuwingen vereist wanneer het 4-MEI-gehalte een drempel overschrijdt. Matig gebruik aanbevolen, vooral bij kinderen." },
  },
  "e160a": {
    name: { de: "Beta-Carotin", ru: "Бета-каротин", pl: "Beta-karoten", nl: "Bètacaroteen" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Oranger Farbstoff, Vorstufe von Vitamin A. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Natürlich und in den üblichen Mengen sicher.", ru: "Оранжевый краситель, предшественник витамина A. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Натуральный и безопасный при обычных уровнях потребления.", pl: "Pomarańczowy barwnik, prekursor witaminy A. Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Naturalny i bezpieczny przy zwykłych poziomach.", nl: "Oranje kleurstof, voorloper van vitamine A. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Natuurlijk en veilig bij gangbare niveaus." },
  },
  "e160c": {
    name: { de: "Paprikaextrakt", ru: "Экстракт паприки", pl: "Ekstrakt z papryki", nl: "Paprika-extract" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Natürlicher rot-oranger Farbstoff aus Paprika. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Keine bekannten Risiken.", ru: "Натуральный красно-оранжевый краситель из перца. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Известных рисков нет.", pl: "Naturalny czerwono-pomarańczowy barwnik z papryki. Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Brak znanych zagrożeń.", nl: "Natuurlijke rood-oranje kleurstof uit paprika's. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Geen bekende risico's." },
  },
  "e163": {
    name: { de: "Anthocyane", ru: "Антоцианы", pl: "Antocyjany", nl: "Anthocyanen" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Natürlicher rot-violetter Farbstoff aus Früchten (Trauben, Beeren). In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Besitzt antioxidative Eigenschaften.", ru: "Натуральный красно-фиолетовый краситель из фруктов (виноград, ягоды). Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Обладает антиоксидантными свойствами.", pl: "Naturalny czerwono-fioletowy barwnik z owoców (winogrona, jagody). Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Ma właściwości przeciwutleniające.", nl: "Natuurlijke rood-paarse kleurstof uit fruit (druiven, bessen). Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Heeft antioxiderende eigenschappen." },
  },
  "e171": {
    name: { de: "Titandioxid", ru: "Диоксид титана", pl: "Dwutlenek tytanu", nl: "Titaandioxide" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Weißer Farbstoff. In der EU als Lebensmittelzusatzstoff seit August 2022 VERBOTEN (Verordnung der Europäischen Kommission 2022/63), nachdem die EFSA 2021 zu dem Schluss kam, dass er aufgrund von Bedenken hinsichtlich der Genotoxizität (DNA-Schädigung) nicht mehr als sicher gelten kann. Frankreich hatte ihn bereits 2019 verboten. In den USA weiterhin erlaubt. Vermeiden.", ru: "Белый краситель. ЗАПРЕЩЁН в ЕС как пищевая добавка с августа 2022 года (Регламент Европейской комиссии 2022/63) после того, как EFSA в 2021 году пришла к выводу, что он больше не может считаться безопасным из-за опасений по поводу генотоксичности (повреждение ДНК). Франция запретила его ещё в 2019 году. В США по-прежнему разрешён. Избегайте.", pl: "Biały barwnik. ZAKAZANY w UE jako dodatek do żywności od sierpnia 2022 roku (Rozporządzenie Komisji Europejskiej 2022/63), po tym jak EFSA w 2021 roku stwierdziła, że nie można go już uznać za bezpieczny z powodu obaw dotyczących genotoksyczności (uszkodzenie DNA). Francja zakazała go już w 2019 roku. Nadal dozwolony w USA. Unikaj.", nl: "Witte kleurstof. VERBODEN in de EU als levensmiddelenadditief sinds augustus 2022 (Verordening van de Europese Commissie 2022/63), nadat de EFSA in 2021 concludeerde dat het niet langer als veilig kan worden beschouwd vanwege zorgen over genotoxiciteit (DNA-schade). Frankrijk had het al in 2019 verboden. Nog steeds toegestaan in de VS. Vermijden." },
  },
  "e172": {
    name: { de: "Eisenoxide", ru: "Оксиды железа", pl: "Tlenki żelaza", nl: "IJzeroxiden" },
    use: { de: "Farbstoff", ru: "краситель", pl: "barwnik", nl: "kleurstof" },
    desc: { de: "Mineralische Farbstoffe (rot, gelb, schwarz). In der EU zugelassen und von der EFSA innerhalb der genehmigten Grenzwerte als sicher eingestuft; weltweit erlaubt.", ru: "Минеральные красители (красный, жёлтый, чёрный). Разрешены в ЕС и признаны EFSA безопасными в пределах утверждённых норм; разрешены во всём мире.", pl: "Barwniki mineralne (czerwony, żółty, czarny). Dozwolone w UE i uznane przez EFSA za bezpieczne w zatwierdzonych granicach; dozwolone na całym świecie.", nl: "Minerale kleurstoffen (rood, geel, zwart). Toegelaten in de EU en door de EFSA als veilig beschouwd binnen de goedgekeurde grenzen; wereldwijd toegestaan." },
  },
  "e200": {
    name: { de: "Sorbinsäure", ru: "Сорбиновая кислота", pl: "Kwas sorbowy", nl: "Sorbinezuur" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff gegen Schimmel und Hefen. In der EU zugelassen und von der EFSA innerhalb der festgelegten Grenzwerte als sicher eingestuft; weltweit erlaubt. Weit verbreitet.", ru: "Консервант против плесени и дрожжей. Разрешён в ЕС и признан EFSA безопасным в пределах установленных норм; разрешён во всём мире. Широко используется.", pl: "Konserwant przeciwko pleśni i drożdżom. Dozwolony w UE i uznany przez EFSA za bezpieczny w ustalonych granicach; dozwolony na całym świecie. Szeroko stosowany.", nl: "Conserveermiddel tegen schimmel en gist. Toegelaten in de EU en door de EFSA als veilig beschouwd binnen de vastgestelde grenzen; wereldwijd toegestaan. Veel gebruikt." },
  },
  "e202": {
    name: { de: "Kaliumsorbat", ru: "Сорбат калия", pl: "Sorbinian potasu", nl: "Kaliumsorbaat" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff, der Schimmel verhindert. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Weit verbreitet, sehr seltene Reaktionen bei empfindlichen Personen.", ru: "Консервант, предотвращающий плесень. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Широко используется, очень редкие реакции у чувствительных людей.", pl: "Konserwant zapobiegający pleśni. Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Szeroko stosowany, bardzo rzadkie reakcje u osób wrażliwych.", nl: "Conserveermiddel dat schimmel voorkomt. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Veel gebruikt, zeer zeldzame reacties bij gevoelige personen." },
  },
  "e210": {
    name: { de: "Benzoesäure", ru: "Бензойная кислота", pl: "Kwas benzoesowy", nl: "Benzoëzuur" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff. In der EU mit von der EFSA festgelegten Grenzwerten zugelassen, kann aber in Kombination mit Vitamin C Benzol bilden (ein Karzinogen, in geringen Mengen). Mögliche Reaktionen bei empfindlichen Personen. Vorsicht.", ru: "Консервант. Разрешён в ЕС с установленными EFSA нормами, но в сочетании с витамином C может образовывать бензол (канцероген, в небольших количествах). Возможны реакции у чувствительных людей. Осторожно.", pl: "Konserwant. Dozwolony w UE z limitami ustalonymi przez EFSA, ale w połączeniu z witaminą C może tworzyć benzen (substancję rakotwórczą, w małych ilościach). Możliwe reakcje u osób wrażliwych. Ostrożnie.", nl: "Conserveermiddel. Toegelaten in de EU met door de EFSA vastgestelde grenzen, maar in combinatie met vitamine C kan het benzeen vormen (een carcinogeen, in kleine hoeveelheden). Mogelijke reacties bij gevoelige personen. Voorzichtigheid." },
  },
  "e211": {
    name: { de: "Natriumbenzoat", ru: "Бензоат натрия", pl: "Benzoesan sodu", nl: "Natriumbenzoaat" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Häufiger Konservierungsstoff. In der EU mit Grenzwerten zugelassen, kann aber in Kombination mit Vitamin C Benzol bilden (geringe Mengen, ein Karzinogen). In der Southampton-Studie wurde er in Verbindung mit künstlichen Farbstoffen mit Hyperaktivität bei Kindern in Zusammenhang gebracht. Vorsicht.", ru: "Распространённый консервант. Разрешён в ЕС с ограничениями, но в сочетании с витамином C может образовывать бензол (небольшие количества, канцероген). В Саутгемптонском исследовании в сочетании с искусственными красителями он был связан с гиперактивностью у детей. Осторожно.", pl: "Powszechny konserwant. Dozwolony w UE z limitami, ale w połączeniu z witaminą C może tworzyć benzen (małe ilości, substancja rakotwórcza). W badaniu z Southampton, w połączeniu ze sztucznymi barwnikami, powiązano go z nadpobudliwością u dzieci. Ostrożnie.", nl: "Veelgebruikt conserveermiddel. Toegelaten in de EU met grenzen, maar in combinatie met vitamine C kan het benzeen vormen (kleine hoeveelheden, een carcinogeen). In de Southampton-studie werd het in combinatie met kunstmatige kleurstoffen in verband gebracht met hyperactiviteit bij kinderen. Voorzichtigheid." },
  },
  "e220": {
    name: { de: "Schwefeldioxid", ru: "Диоксид серы", pl: "Dwutlenek siarki", nl: "Zwaveldioxide" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff und Antioxidans, häufig in Wein und Trockenfrüchten. In der EU zugelassen, gehört aber zu den 14 Allergenen, deren Kennzeichnung auf dem Etikett verpflichtend ist (Verordnung 1169/2011): kann Asthmaanfälle und Reaktionen bei empfindlichen Personen auslösen. Vorsicht.", ru: "Консервант и антиоксидант, часто встречается в вине и сухофруктах. Разрешён в ЕС, но входит в число 14 аллергенов, обязательных к указанию на этикетке (Регламент 1169/2011): может вызывать приступы астмы и реакции у чувствительных людей. Осторожно.", pl: "Konserwant i przeciwutleniacz, częsty w winie i suszonych owocach. Dozwolony w UE, ale należy do 14 alergenów, których oznakowanie na etykiecie jest obowiązkowe (Rozp. 1169/2011): może wywoływać ataki astmy i reakcje u osób wrażliwych. Ostrożnie.", nl: "Conserveermiddel en antioxidant, vaak in wijn en gedroogd fruit. Toegelaten in de EU, maar het is een van de 14 allergenen waarvan de etikettering verplicht is (Verordening 1169/2011): kan astma-aanvallen en reacties bij gevoelige personen uitlokken. Voorzichtigheid." },
  },
  "e223": {
    name: { de: "Natriummetabisulfit", ru: "Метабисульфит натрия", pl: "Pirosiarczyn sodu", nl: "Natriummetabisulfiet" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff auf Sulfitbasis. In der EU zugelassen, doch Sulfite sind Allergene mit verpflichtender Kennzeichnung (Verordnung 1169/2011): können Reaktionen bei Asthmatikern und empfindlichen Personen hervorrufen. Vorsicht.", ru: "Консервант на основе сульфитов. Разрешён в ЕС, но сульфиты являются аллергенами, обязательными к указанию на этикетке (Регламент 1169/2011): могут вызывать реакции у астматиков и чувствительных людей. Осторожно.", pl: "Konserwant na bazie siarczynów. Dozwolony w UE, ale siarczyny są alergenami o obowiązkowym oznakowaniu na etykiecie (Rozp. 1169/2011): mogą wywoływać reakcje u astmatyków i osób wrażliwych. Ostrożnie.", nl: "Conserveermiddel op basis van sulfieten. Toegelaten in de EU, maar sulfieten zijn allergenen met verplichte etikettering (Verordening 1169/2011): kunnen reacties veroorzaken bij astmapatiënten en gevoelige personen. Voorzichtigheid." },
  },
  "e250": {
    name: { de: "Natriumnitrit", ru: "Нитрит натрия", pl: "Azotyn sodu", nl: "Natriumnitriet" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff in Pökelwaren. In der EU zugelassen, doch 2023 hat die Europäische Kommission die zulässigen Grenzwerte gesenkt (Verordnung 2023/2108), weil er Nitrosamine bilden kann (mit erhöhtem Krebsrisiko verbunden, besonders Darmkrebs). Die WHO stuft verarbeitetes Fleisch als krebserregend ein. Reales Risiko bei häufigem Verzehr.", ru: "Консервант в мясных продуктах. Разрешён в ЕС, но в 2023 году Европейская комиссия снизила допустимые нормы (Регламент 2023/2108), поскольку он может образовывать нитрозамины (связаны с повышенным риском рака, особенно колоректального). ВОЗ классифицирует переработанное мясо как канцерогенное. Реальный риск при частом потреблении.", pl: "Konserwant w wędlinach. Dozwolony w UE, ale w 2023 roku Komisja Europejska obniżyła dopuszczalne limity (Rozp. 2023/2108), ponieważ może tworzyć nitrozoaminy (związane z podwyższonym ryzykiem raka, zwłaszcza jelita grubego). WHO klasyfikuje przetworzone mięso jako rakotwórcze. Realne ryzyko przy częstym spożyciu.", nl: "Conserveermiddel in vleeswaren. Toegelaten in de EU, maar in 2023 heeft de Europese Commissie de toegestane grenzen verlaagd (Verordening 2023/2108), omdat het nitrosamines kan vormen (in verband gebracht met een verhoogd kankerrisico, vooral darmkanker). De WHO classificeert bewerkt vlees als kankerverwekkend. Reëel risico bij frequent gebruik." },
  },
  "e251": {
    name: { de: "Natriumnitrat", ru: "Нитрат натрия", pl: "Azotan sodu", nl: "Natriumnitraat" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Ähnlich wie Nitrit, in Pökelwaren. In der EU zugelassen, mit 2023 gesenkten Grenzwerten (Verordnung 2023/2108). Wandelt sich in Nitrite und dann in Nitrosamine um (Krebsrisiko). Die WHO bringt verarbeitetes Fleisch mit dem Krebsrisiko in Verbindung. Begrenzter Verzehr empfohlen.", ru: "Похож на нитрит, в мясных продуктах. Разрешён в ЕС со сниженными в 2023 году нормами (Регламент 2023/2108). Превращается в нитриты, а затем в нитрозамины (риск рака). ВОЗ связывает переработанное мясо с риском рака. Рекомендуется ограниченное потребление.", pl: "Podobny do azotynu, w wędlinach. Dozwolony w UE z limitami obniżonymi w 2023 roku (Rozp. 2023/2108). Przekształca się w azotyny, a następnie w nitrozoaminy (ryzyko raka). WHO wiąże przetworzone mięso z ryzykiem raka. Zalecane ograniczone spożycie.", nl: "Vergelijkbaar met nitriet, in vleeswaren. Toegelaten in de EU met in 2023 verlaagde grenzen (Verordening 2023/2108). Wordt omgezet in nitrieten en vervolgens nitrosamines (kankerrisico). De WHO brengt bewerkt vlees in verband met kankerrisico. Beperkt gebruik aanbevolen." },
  },
  "e252": {
    name: { de: "Kaliumnitrat", ru: "Нитрат калия", pl: "Azotan potasu", nl: "Kaliumnitraat" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff in Wurstwaren und Käse. In der EU zugelassen, mit 2023 überarbeiteten Grenzwerten (Reg. 2023/2108). Kann sich in Nitrosamine umwandeln (Krebsrisiko). Begrenzter Verzehr empfohlen.", ru: "Консервант в колбасных изделиях и сырах. Разрешён в ЕС, предельные нормы пересмотрены в 2023 году (Reg. 2023/2108). Может превращаться в нитрозамины (риск рака). Рекомендуется ограниченное потребление.", pl: "Konserwant w wędlinach i serach. Dopuszczony w UE, limity zmienione w 2023 roku (Reg. 2023/2108). Może przekształcać się w nitrozaminy (ryzyko nowotworu). Zalecane ograniczone spożycie.", nl: "Conserveermiddel in vleeswaren en kaas. Toegestaan in de EU, met in 2023 herziene limieten (Reg. 2023/2108). Kan zich omzetten in nitrosaminen (kankerrisico). Beperkte inname aangeraden." },
  },
  "e260": {
    name: { de: "Essigsäure (Essig)", ru: "Уксусная кислота (уксус)", pl: "Kwas octowy (ocet)", nl: "Azijnzuur (azijn)" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Hauptbestandteil von Essig. In der EU ohne strengen Grenzwert zugelassen (quantum satis) und von der EFSA als sicher eingestuft; weltweit erlaubt. Wird zur Konservierung und für den Geschmack verwendet.", ru: "Главный компонент уксуса. Разрешена в ЕС без строгого предела (quantum satis) и признана EFSA безопасной; разрешена во всём мире. Используется для консервации и вкуса.", pl: "Główny składnik octu. Dopuszczony w UE bez ścisłego limitu (quantum satis) i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Stosowany do konserwacji i nadawania smaku.", nl: "Hoofdbestanddeel van azijn. Toegestaan in de EU zonder strikte limiet (quantum satis) en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Gebruikt voor conservering en smaak." },
  },
  "e270": {
    name: { de: "Milchsäure", ru: "Молочная кислота", pl: "Kwas mlekowy", nl: "Melkzuur" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Natürliche Säure aus der Fermentation (Joghurt, Eingelegtes). In der EU ohne strengen Grenzwert zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Натуральная кислота, образующаяся при брожении (йогурт, соленья). Разрешена в ЕС без строгого предела и признана EFSA безопасной; разрешена во всём мире.", pl: "Naturalny kwas powstający w wyniku fermentacji (jogurt, kiszonki). Dopuszczony w UE bez ścisłego limitu i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Natuurlijk zuur uit fermentatie (yoghurt, ingemaakte groenten). Toegestaan in de EU zonder strikte limiet en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e280": {
    name: { de: "Propionsäure", ru: "Пропионовая кислота", pl: "Kwas propionowy", nl: "Propionzuur" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff in Brot und Backwaren, gegen Schimmel. In der EU zugelassen und von der EFSA innerhalb der festgelegten Grenzwerte als sicher eingestuft; weltweit erlaubt.", ru: "Консервант в хлебе и хлебобулочных изделиях, против плесени. Разрешён в ЕС и признан EFSA безопасным в установленных пределах; разрешён во всём мире.", pl: "Konserwant w chlebie i wyrobach piekarniczych, przeciw pleśni. Dopuszczony w UE i uznany przez EFSA za bezpieczny w ustalonych granicach; dozwolony na całym świecie.", nl: "Conserveermiddel in brood en bakwaren, tegen schimmel. Toegestaan in de EU en door de EFSA binnen de vastgestelde limieten als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e290": {
    name: { de: "Kohlendioxid", ru: "Диоксид углерода", pl: "Dwutlenek węgla", nl: "Kooldioxide" },
    use: { de: "Karbonisierungsgas", ru: "газ для газирования", pl: "gaz do nasycania", nl: "koolzuurgas" },
    desc: { de: "Das Gas, das Getränke sprudelnd macht. In der EU ohne strengen Grenzwert zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Газ, который делает напитки газированными. Разрешён в ЕС без строгого предела и признан EFSA безопасным; разрешён во всём мире.", pl: "Gaz, który nadaje napojom musujący charakter. Dopuszczony w UE bez ścisłego limitu i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Het gas dat dranken bruisend maakt. Toegestaan in de EU zonder strikte limiet en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e296": {
    name: { de: "Apfelsäure", ru: "Яблочная кислота", pl: "Kwas jabłkowy", nl: "Appelzuur" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Natürliche Säure aus Äpfeln, für einen säuerlichen Geschmack. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Натуральная кислота из яблок, для кисловатого вкуса. Разрешена в ЕС и признана EFSA безопасной; разрешена во всём мире.", pl: "Naturalny kwas z jabłek, nadający kwaskowaty smak. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Natuurlijk zuur uit appels, voor een zure smaak. Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e300": {
    name: { de: "Ascorbinsäure (Vit. C)", ru: "Аскорбиновая кислота (вит. C)", pl: "Kwas askorbinowy (wit. C)", nl: "Ascorbinezuur (vit. C)" },
    use: { de: "Antioxidationsmittel", ru: "антиоксидант", pl: "przeciwutleniacz", nl: "antioxidant" },
    desc: { de: "Vitamin C, als Antioxidationsmittel verwendet. In der EU ohne strengen Grenzwert zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Sogar nützlich.", ru: "Витамин C, используется как антиоксидант. Разрешён в ЕС без строгого предела и признан EFSA безопасным; разрешён во всём мире. Даже полезен.", pl: "Witamina C, stosowana jako przeciwutleniacz. Dopuszczony w UE bez ścisłego limitu i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Wręcz korzystny.", nl: "Vitamine C, gebruikt als antioxidant. Toegestaan in de EU zonder strikte limiet en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Zelfs gunstig." },
  },
  "e301": {
    name: { de: "Natriumascorbat", ru: "Аскорбат натрия", pl: "Askorbinian sodu", nl: "Natriumascorbaat" },
    use: { de: "Antioxidationsmittel", ru: "антиоксидант", pl: "przeciwutleniacz", nl: "antioxidant" },
    desc: { de: "Eine Form von Vitamin C, Antioxidationsmittel. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Форма витамина C, антиоксидант. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Forma witaminy C, przeciwutleniacz. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Een vorm van vitamine C, antioxidant. Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e306": {
    name: { de: "Tocopherole (Vit. E)", ru: "Токоферолы (вит. E)", pl: "Tokoferole (wit. E)", nl: "Tocoferolen (vit. E)" },
    use: { de: "Antioxidationsmittel", ru: "антиоксидант", pl: "przeciwutleniacz", nl: "antioxidant" },
    desc: { de: "Natürliches Vitamin E, Antioxidationsmittel. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Nützlich.", ru: "Натуральный витамин E, антиоксидант. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Полезен.", pl: "Naturalna witamina E, przeciwutleniacz. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Korzystny.", nl: "Natuurlijke vitamine E, antioxidant. Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Gunstig." },
  },
  "e322": {
    name: { de: "Lecithine", ru: "Лецитины", pl: "Lecytyny", nl: "Lecithinen" },
    use: { de: "Emulgator", ru: "эмульгатор", pl: "emulgator", nl: "emulgator" },
    desc: { de: "Natürlicher Emulgator (aus Soja oder Sonnenblume). In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Natürlich in vielen Lebensmitteln vorhanden. Wenn aus Soja gewonnen, ist Soja in der EU ein kennzeichnungspflichtiges Allergen.", ru: "Натуральный эмульгатор (из сои или подсолнечника). Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Естественно присутствует во многих продуктах. Если получен из сои, соя является аллергеном, подлежащим обязательной маркировке в ЕС.", pl: "Naturalny emulgator (z soi lub słonecznika). Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Naturalnie obecny w wielu produktach. Jeśli pochodzi z soi, soja jest alergenem podlegającym obowiązkowemu oznakowaniu w UE.", nl: "Natuurlijke emulgator (uit soja of zonnebloem). Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Van nature aanwezig in veel voedingsmiddelen. Indien gemaakt van soja, is soja in de EU een allergeen met verplichte etikettering." },
  },
  "e325": {
    name: { de: "Natriumlactat", ru: "Лактат натрия", pl: "Mleczan sodu", nl: "Natriumlactaat" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Salz der Milchsäure, für Säuregrad und Feuchtigkeit. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Соль молочной кислоты, для кислотности и удержания влаги. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Sól kwasu mlekowego, do regulacji kwasowości i wilgotności. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Zout van melkzuur, voor zuurgraad en vochtigheid. Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e330": {
    name: { de: "Zitronensäure", ru: "Лимонная кислота", pl: "Kwas cytrynowy", nl: "Citroenzuur" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Natürliche Säure aus Zitrusfrüchten, für sauren Geschmack und Konservierung. In der EU ohne strengen Grenzwert zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Natürlich in Früchten vorhanden.", ru: "Натуральная кислота из цитрусовых, для кислого вкуса и консервации. Разрешена в ЕС без строгого предела и признана EFSA безопасной; разрешена во всём мире. Естественно присутствует во фруктах.", pl: "Naturalny kwas z owoców cytrusowych, do nadawania kwaśnego smaku i konserwacji. Dopuszczony w UE bez ścisłego limitu i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Naturalnie obecny w owocach.", nl: "Natuurlijk zuur uit citrusvruchten, voor zure smaak en conservering. Toegestaan in de EU zonder strikte limiet en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Van nature aanwezig in fruit." },
  },
  "e331": {
    name: { de: "Natriumcitrate", ru: "Цитраты натрия", pl: "Cytryniany sodu", nl: "Natriumcitraten" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Salze der Zitronensäure, zur Regulierung des Säuregrads. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Соли лимонной кислоты, для регулирования кислотности. Разрешены в ЕС и признаны EFSA безопасными; разрешены во всём мире.", pl: "Sole kwasu cytrynowego, do regulacji kwasowości. Dopuszczone w UE i uznane przez EFSA za bezpieczne; dozwolone na całym świecie.", nl: "Zouten van citroenzuur, voor het reguleren van de zuurgraad. Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e333": {
    name: { de: "Calciumcitrate", ru: "Цитраты кальция", pl: "Cytryniany wapnia", nl: "Calciumcitraten" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Calciumsalze der Zitronensäure. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Liefern zudem Calcium.", ru: "Кальциевые соли лимонной кислоты. Разрешены в ЕС и признаны EFSA безопасными; разрешены во всём мире. Также служат источником кальция.", pl: "Sole wapniowe kwasu cytrynowego. Dopuszczone w UE i uznane przez EFSA za bezpieczne; dozwolone na całym świecie. Dostarczają również wapnia.", nl: "Calciumzouten van citroenzuur. Toegestaan in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Leveren ook calcium." },
  },
  "e338": {
    name: { de: "Phosphorsäure", ru: "Фосфорная кислота", pl: "Kwas fosforowy", nl: "Fosforzuur" },
    use: { de: "Säuerungsmittel", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurregelaar" },
    desc: { de: "Säuerungsmittel vor allem in Cola-Getränken. In der EU zugelassen, doch 2019 legte die EFSA erstmals eine maximale Tagesdosis für (Gesamt-)Phosphate fest, wegen des kardiovaskulären Risikos bei hohem Verzehr. Häufiger Konsum wird zudem mit Zahnerosion und verminderter Knochendichte in Verbindung gebracht. Cola ist die Hauptquelle.", ru: "Регулятор кислотности, прежде всего в напитках кола. Разрешена в ЕС, но в 2019 году EFSA впервые установила максимальную суточную дозу для (общих) фосфатов из-за сердечно-сосудистого риска при высоком потреблении. Частое употребление также связывают с эрозией зубов и снижением плотности костей. Кола — основной источник.", pl: "Regulator kwasowości, głównie w napojach typu cola. Dopuszczony w UE, ale w 2019 roku EFSA po raz pierwszy ustaliła maksymalną dzienną dawkę dla fosforanów (ogółem) ze względu na ryzyko sercowo-naczyniowe przy wysokim spożyciu. Częste spożycie wiąże się też z erozją zębów i obniżeniem gęstości kości. Cola jest głównym źródłem.", nl: "Zuurregelaar, vooral in coladranken. Toegelaten in de EU, maar in 2019 stelde de EFSA voor het eerst een maximale dagelijkse dosis vast voor (totale) fosfaten vanwege het cardiovasculaire risico bij hoge consumptie. Frequent gebruik wordt ook in verband gebracht met tanderosie en verminderde botdichtheid. Cola is de belangrijkste bron." },
  },
  "e339": {
    name: { de: "Natriumphosphate", ru: "Фосфаты натрия", pl: "Fosforany sodu", nl: "Natriumfosfaten" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurregelaar" },
    desc: { de: "Phosphathaltige Zusatzstoffe. In der EU zugelassen, doch 2019 empfahl die EFSA, die Gesamtaufnahme von Phosphaten zu begrenzen, da sie bei hohem Verzehr mit einem kardiovaskulären Risiko verbunden ist. In Maßen.", ru: "Добавки на основе фосфатов. Разрешены в ЕС, но в 2019 году EFSA рекомендовала ограничить общее потребление фосфатов, связанное с сердечно-сосудистым риском при высоком потреблении. Умеренно.", pl: "Dodatki na bazie fosforanów. Dopuszczone w UE, ale w 2019 roku EFSA zaleciła ograniczenie całkowitego spożycia fosforanów, wiązanego z ryzykiem sercowo-naczyniowym przy wysokim spożyciu. Z umiarem.", nl: "Fosfaathoudende additieven. Toegelaten in de EU, maar in 2019 adviseerde de EFSA de totale inname van fosfaten te beperken, die bij hoge consumptie in verband wordt gebracht met een cardiovasculair risico. Met mate." },
  },
  "e340": {
    name: { de: "Kaliumphosphate", ru: "Фосфаты калия", pl: "Fosforany potasu", nl: "Kaliumfosfaten" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurregelaar" },
    desc: { de: "Phosphathaltige Zusatzstoffe. In der EU zugelassen, doch 2019 empfahl die EFSA, die Gesamtaufnahme von Phosphaten zu begrenzen, da sie mit einem kardiovaskulären Risiko verbunden ist. In Maßen.", ru: "Добавки на основе фосфатов. Разрешены в ЕС, но в 2019 году EFSA рекомендовала ограничить общее потребление фосфатов, связанное с сердечно-сосудистым риском. Умеренно.", pl: "Dodatki na bazie fosforanów. Dopuszczone w UE, ale w 2019 roku EFSA zaleciła ograniczenie całkowitego spożycia fosforanów, wiązanego z ryzykiem sercowo-naczyniowym. Z umiarem.", nl: "Fosfaathoudende additieven. Toegelaten in de EU, maar in 2019 adviseerde de EFSA de totale inname van fosfaten te beperken, die in verband wordt gebracht met een cardiovasculair risico. Met mate." },
  },
  "e375": {
    name: { de: "Niacin (Vit. B3)", ru: "Ниацин (вит. B3)", pl: "Niacyna (wit. B3)", nl: "Niacine (vit. B3)" },
    use: { de: "Vitamin", ru: "витамин", pl: "witamina", nl: "vitamine" },
    desc: { de: "Vitamin B3, als Nährstoff zugesetzt. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Витамин B3, добавляемый как питательное вещество. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Witamina B3, dodawana jako składnik odżywczy. Dopuszczona w UE i uznana przez EFSA za bezpieczną; dozwolona na całym świecie.", nl: "Vitamine B3, toegevoegd als voedingsstof. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e385": {
    name: { de: "Calcium-Dinatrium-EDTA", ru: "Кальций-динатриевая ЭДТА", pl: "EDTA wapniowo-disodowy", nl: "Calciumdinatrium-EDTA" },
    use: { de: "Antioxidationsmittel", ru: "антиоксидант", pl: "przeciwutleniacz", nl: "antioxidant" },
    desc: { de: "Chelatbildner, der Farbe und Geschmack schützt. In der EU innerhalb strenger, von der EFSA festgelegter Grenzwerte zugelassen; ein hoher Verzehr wird nicht empfohlen. In Maßen.", ru: "Хелатирующий агент, защищающий цвет и вкус. Разрешён в ЕС в строгих пределах, установленных EFSA; высокое потребление не рекомендуется. Умеренно.", pl: "Czynnik chelatujący chroniący barwę i smak. Dopuszczony w UE w ścisłych granicach ustalonych przez EFSA; wysokie spożycie niewskazane. Z umiarem.", nl: "Chelaatvormer die kleur en smaak beschermt. Toegelaten in de EU binnen strikte, door de EFSA vastgestelde grenzen; hoge inname wordt afgeraden. Met mate." },
  },
  "e406": {
    name: { de: "Agar-Agar", ru: "Агар-агар", pl: "Agar", nl: "Agar-agar" },
    use: { de: "Geliermittel", ru: "желирующий агент", pl: "substancja żelująca", nl: "geleermiddel" },
    desc: { de: "Natürliches Geliermittel aus Algen. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Pflanzliche Alternative zu Gelatine.", ru: "Натуральный желирующий агент из водорослей. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Растительная альтернатива желатину.", pl: "Naturalna substancja żelująca z alg. Dopuszczona w UE i uznana przez EFSA za bezpieczną; dozwolona na całym świecie. Roślinna alternatywa dla żelatyny.", nl: "Natuurlijk geleermiddel uit zeewier. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Plantaardig alternatief voor gelatine." },
  },
  "e407": {
    name: { de: "Carrageen", ru: "Каррагинан", pl: "Karagen", nl: "Carrageen" },
    use: { de: "Geliermittel", ru: "желирующий агент", pl: "substancja żelująca", nl: "geleermiddel" },
    desc: { de: "Geliermittel aus Algen. In der EU zugelassen, doch 2018 forderte die EFSA weitere Daten an, da Tierstudien bei hohen Mengen auf eine mögliche Darmentzündung hindeuten. In der EU ist es in Säuglingsanfangsnahrung verboten. In Maßen.", ru: "Желирующий агент из водорослей. Разрешён в ЕС, но в 2018 году EFSA запросила дополнительные данные, поскольку исследования на животных указывают на возможное воспаление кишечника при больших количествах. В ЕС запрещён в детских смесях для грудных детей. Умеренно.", pl: "Substancja żelująca z alg. Dopuszczona w UE, ale w 2018 roku EFSA zażądała dodatkowych danych, ponieważ badania na zwierzętach sugerują możliwe zapalenie jelit przy dużych ilościach. W UE jest zakazana w preparatach dla niemowląt. Z umiarem.", nl: "Geleermiddel uit zeewier. Toegelaten in de EU, maar in 2018 vroeg de EFSA aanvullende gegevens, omdat dierstudies wijzen op mogelijke darmontsteking bij hoge hoeveelheden. In de EU is het verboden in zuigelingenvoeding. Met mate." },
  },
  "e410": {
    name: { de: "Johannisbrotkernmehl", ru: "Камедь рожкового дерева", pl: "Mączka chleba świętojańskiego", nl: "Johannesbroodpitmeel" },
    use: { de: "Stabilisator", ru: "стабилизатор", pl: "stabilizator", nl: "stabilisator" },
    desc: { de: "Natürlicher Stabilisator aus Johannisbrotkernen. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Natürliche Faser.", ru: "Натуральный стабилизатор из семян рожкового дерева. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Натуральная клетчатка.", pl: "Naturalny stabilizator z nasion chleba świętojańskiego. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Naturalny błonnik.", nl: "Natuurlijke stabilisator uit johannesbroodpitten. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Natuurlijke vezel." },
  },
  "e412": {
    name: { de: "Guarkernmehl", ru: "Гуаровая камедь", pl: "Guma guar", nl: "Guarpitmeel" },
    use: { de: "Stabilisator", ru: "стабилизатор", pl: "stabilizator", nl: "stabilisator" },
    desc: { de: "Natürlicher Stabilisator aus Guarsamen. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. In großen Mengen kann er die Verdauung beeinflussen. Natürliche Faser.", ru: "Натуральный стабилизатор из семян гуара. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. В больших количествах может влиять на пищеварение. Натуральная клетчатка.", pl: "Naturalny stabilizator z nasion guar. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. W dużych ilościach może wpływać na trawienie. Naturalny błonnik.", nl: "Natuurlijke stabilisator uit guarzaden. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. In grote hoeveelheden kan het een effect op de spijsvertering hebben. Natuurlijke vezel." },
  },
  "e414": {
    name: { de: "Gummi arabicum", ru: "Гуммиарабик", pl: "Guma arabska", nl: "Arabische gom" },
    use: { de: "Stabilisator", ru: "стабилизатор", pl: "stabilizator", nl: "stabilisator" },
    desc: { de: "Natürlicher Stabilisator aus dem Akazienbaum. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Seit Jahrhunderten verwendet.", ru: "Натуральный стабилизатор из дерева акации. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Используется веками.", pl: "Naturalny stabilizator z drzewa akacjowego. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Stosowany od wieków.", nl: "Natuurlijke stabilisator uit de acaciaboom. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Al eeuwenlang gebruikt." },
  },
  "e415": {
    name: { de: "Xanthan", ru: "Ксантановая камедь", pl: "Guma ksantanowa", nl: "Xanthaangom" },
    use: { de: "Stabilisator", ru: "стабилизатор", pl: "stabilizator", nl: "stabilisator" },
    desc: { de: "Durch Fermentation gewonnener Stabilisator. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Weit verbreitet, auch in glutenfreien Produkten.", ru: "Стабилизатор, получаемый ферментацией. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире. Широко используется, в том числе в безглютеновых продуктах.", pl: "Stabilizator otrzymywany w wyniku fermentacji. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie. Szeroko stosowany, także w produktach bezglutenowych.", nl: "Stabilisator verkregen door fermentatie. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Veel gebruikt, ook in glutenvrije producten." },
  },
  "e420": {
    name: { de: "Sorbit", ru: "Сорбит", pl: "Sorbitol", nl: "Sorbitol" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Kalorienärmeres Süßungsmittel. In der EU zugelassen und von der EFSA als sicher eingestuft, doch die EU verlangt bei Produkten mit über 10 % Polyolen den Hinweis \"übermäßiger Verzehr kann abführend wirken\". In Maßen.", ru: "Подсластитель с пониженной калорийностью. Разрешён в ЕС и признан EFSA безопасным, но ЕС требует указывать \"чрезмерное потребление может оказывать слабительное действие\" на продуктах, содержащих более 10% полиолов. Умеренно.", pl: "Substancja słodząca o niższej kaloryczności. Dopuszczona w UE i uznana przez EFSA za bezpieczną, ale UE wymaga umieszczania informacji \"nadmierne spożycie może mieć efekt przeczyszczający\" na produktach zawierających ponad 10% polioli. Z umiarem.", nl: "Caloriearmere zoetstof. Toegelaten in de EU en door de EFSA als veilig beschouwd, maar de EU vereist de vermelding \"overmatig gebruik kan een laxerend effect hebben\" op producten met meer dan 10% polyolen. Met mate." },
  },
  "e422": {
    name: { de: "Glycerin (Glycerol)", ru: "Глицерин (глицерол)", pl: "Glicerol (gliceryna)", nl: "Glycerol (glycerine)" },
    use: { de: "Feuchthaltemittel", ru: "влагоудерживающий агент", pl: "substancja utrzymująca wilgoć", nl: "vochtvasthoudend middel" },
    desc: { de: "Hält Produkte feucht. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Удерживает влагу в продуктах. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Utrzymuje wilgotność produktów. Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Houdt producten vochtig. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e440": {
    name: { de: "Pektin", ru: "Пектин", pl: "Pektyna", nl: "Pectine" },
    use: { de: "Geliermittel", ru: "желирующий агент", pl: "substancja żelująca", nl: "geleermiddel" },
    desc: { de: "Natürliches Geliermittel aus Obst, in Marmeladen verwendet. In der EU ohne strengen Grenzwert zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt. Natürliche Faser.", ru: "Натуральный желирующий агент из фруктов, используется в джемах. Разрешён в ЕС без строгого ограничения и признан EFSA безопасным; разрешён во всём мире. Натуральная клетчатка.", pl: "Naturalna substancja żelująca z owoców, stosowana w dżemach. Dopuszczona w UE bez ścisłego limitu i uznana przez EFSA za bezpieczną; dozwolona na całym świecie. Naturalny błonnik.", nl: "Natuurlijk geleermiddel uit fruit, gebruikt in jam. Toegelaten in de EU zonder strikte limiet en door de EFSA als veilig beschouwd; wereldwijd toegestaan. Natuurlijke vezel." },
  },
  "e450": {
    name: { de: "Diphosphate", ru: "Дифосфаты", pl: "Difosforany", nl: "Difosfaten" },
    use: { de: "Backtriebmittel", ru: "разрыхлитель", pl: "substancja spulchniająca", nl: "rijsmiddel" },
    desc: { de: "Phosphatzusätze, in Backwaren und verarbeitetem Fleisch. In der EU zugelassen, doch 2019 empfahl die EFSA, die Gesamtaufnahme von Phosphaten zu begrenzen (kardiovaskuläres Risiko). In Maßen.", ru: "Фосфатные добавки, в выпечке и переработанном мясе. Разрешены в ЕС, но в 2019 году EFSA рекомендовало ограничить общее потребление фосфатов (сердечно-сосудистый риск). Умеренно.", pl: "Dodatki fosforanowe, w wyrobach piekarskich i przetworach mięsnych. Dozwolone w UE, ale w 2019 roku EFSA zaleciła ograniczenie całkowitego spożycia fosforanów (ryzyko sercowo-naczyniowe). Z umiarem.", nl: "Fosfaatadditieven, in bakwaren en bewerkt vlees. Toegelaten in de EU, maar in 2019 adviseerde de EFSA om de totale fosfaatinname te beperken (cardiovasculair risico). Met mate." },
  },
  "e466": {
    name: { de: "Carboxymethylcellulose (CMC)", ru: "Карбоксиметилцеллюлоза (КМЦ)", pl: "Karboksymetyloceluloza (CMC)", nl: "Carboxymethylcellulose (CMC)" },
    use: { de: "Stabilisator", ru: "стабилизатор", pl: "stabilizator", nl: "stabilisator" },
    desc: { de: "Stabilisator und Verdickungsmittel. In der EU zugelassen und von der EFSA als sicher eingestuft, doch neuere Studien untersuchen die Wirkung von Emulgatoren auf die Darmflora. In Maßen.", ru: "Стабилизатор и загуститель. Разрешён в ЕС и признан EFSA безопасным, однако недавние исследования изучают влияние эмульгаторов на микрофлору кишечника. Умеренно.", pl: "Stabilizator i substancja zagęszczająca. Dozwolony w UE i uznany przez EFSA za bezpieczny, ale najnowsze badania analizują wpływ emulgatorów na florę jelitową. Z umiarem.", nl: "Stabilisator en verdikkingsmiddel. Toegelaten in de EU en door de EFSA als veilig beschouwd, maar recente studies onderzoeken het effect van emulgatoren op de darmflora. Met mate." },
  },
  "e471": {
    name: { de: "Mono- und Diglyceride", ru: "Моно- и диглицериды", pl: "Mono- i diglicerydy", nl: "Mono- en diglyceriden" },
    use: { de: "Emulgator", ru: "эмульгатор", pl: "emulgator", nl: "emulgator" },
    desc: { de: "Emulgator auf Fettbasis. In der EU ohne strenge Höchstmenge zugelassen und weit verbreitet. Kann Spuren von Transfetten enthalten. Neuere Forschung untersucht die Wirkung von Emulgatoren auf die Darmflora. In Maßen.", ru: "Эмульгатор на основе жиров. Разрешён в ЕС без строгого ограничения и широко используется. Может содержать следы трансжиров. Недавние исследования изучают влияние эмульгаторов на микрофлору кишечника. Умеренно.", pl: "Emulgator na bazie tłuszczów. Dozwolony w UE bez ścisłego limitu i powszechnie stosowany. Może zawierać śladowe ilości tłuszczów trans. Najnowsze badania analizują wpływ emulgatorów na florę jelitową. Z umiarem.", nl: "Emulgator op vetbasis. Toegelaten in de EU zonder strikte limiet en veel gebruikt. Kan sporen van transvetten bevatten. Recent onderzoek bestudeert het effect van emulgatoren op de darmflora. Met mate." },
  },
  "e472e": {
    name: { de: "Mono-/Diglycerid-Ester", ru: "Эфиры моно- и диглицеридов", pl: "Estry mono-/diglicerydów", nl: "Esters van mono-/diglyceriden" },
    use: { de: "Emulgator", ru: "эмульгатор", pl: "emulgator", nl: "emulgator" },
    desc: { de: "In Backwaren häufig verwendeter Emulgator. In der EU zugelassen und von der EFSA als sicher eingestuft. In Maßen, wie bei anderen Emulgatoren.", ru: "Эмульгатор, часто встречающийся в выпечке. Разрешён в ЕС и признан EFSA безопасным. Умеренно, как и с другими эмульгаторами.", pl: "Emulgator powszechny w wyrobach piekarskich. Dozwolony w UE i uznany przez EFSA za bezpieczny. Z umiarem, jak w przypadku innych emulgatorów.", nl: "Emulgator die vaak in bakwaren voorkomt. Toegelaten in de EU en door de EFSA als veilig beschouwd. Met mate, zoals bij andere emulgatoren." },
  },
  "e476": {
    name: { de: "Polyglycerin-Polyricinoleat", ru: "Полиглицерин полирицинолеат", pl: "Polirycynooleinian poliglicerolu", nl: "Polyglycerolpolyricinoleaat" },
    use: { de: "Emulgator", ru: "эмульгатор", pl: "emulgator", nl: "emulgator" },
    desc: { de: "In Schokolade häufig verwendeter Emulgator. In der EU innerhalb der von der EFSA festgelegten Grenzwerte zugelassen. In Maßen.", ru: "Эмульгатор, часто используемый в шоколаде. Разрешён в ЕС в пределах, установленных EFSA. Умеренно.", pl: "Emulgator powszechny w czekoladzie. Dozwolony w UE w granicach ustalonych przez EFSA. Z umiarem.", nl: "Emulgator die veel in chocolade voorkomt. Toegelaten in de EU binnen de door de EFSA vastgestelde limieten. Met mate." },
  },
  "e500": {
    name: { de: "Natriumhydrogencarbonat", ru: "Гидрокарбонат натрия (пищевая сода)", pl: "Wodorowęglan sodu", nl: "Natriumbicarbonaat" },
    use: { de: "Backtriebmittel", ru: "разрыхлитель", pl: "substancja spulchniająca", nl: "rijsmiddel" },
    desc: { de: "Das gewöhnliche Backpulver-Natron, das den Teig aufgehen lässt. In der EU ohne strenge Höchstmenge zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Обычная пищевая сода, заставляющая тесто подниматься. Разрешена в ЕС без строгого ограничения и признана EFSA безопасной; разрешена во всём мире.", pl: "Zwykła soda oczyszczona, sprawiająca, że ciasto rośnie. Dozwolona w UE bez ścisłego limitu i uznana przez EFSA za bezpieczną; dozwolona na całym świecie.", nl: "De gewone baksoda, die het deeg laat rijzen. Toegelaten in de EU zonder strikte limiet en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e503": {
    name: { de: "Ammoniumcarbonat", ru: "Карбонат аммония", pl: "Węglan amonu", nl: "Ammoniumcarbonaat" },
    use: { de: "Backtriebmittel", ru: "разрыхлитель", pl: "substancja spulchniająca", nl: "rijsmiddel" },
    desc: { de: "Traditionelles Backtriebmittel für Kekse. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Традиционный разрыхлитель для печенья. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Tradycyjna substancja spulchniająca do ciastek. Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Traditioneel rijsmiddel voor koekjes. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e509": {
    name: { de: "Calciumchlorid", ru: "Хлорид кальция", pl: "Chlorek wapnia", nl: "Calciumchloride" },
    use: { de: "Festigungsmittel", ru: "уплотнитель", pl: "substancja utwardzająca", nl: "verstevigingsmiddel" },
    desc: { de: "Erhält die Festigkeit von eingemachtem Gemüse und Obst. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Сохраняет упругость консервированных овощей и фруктов. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Utrzymuje jędrność warzyw i owoców w konserwach. Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Houdt ingemaakte groenten en fruit stevig. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e575": {
    name: { de: "Glucono-delta-Lacton", ru: "Глюконо-дельта-лактон", pl: "Glukono-delta-lakton", nl: "Glucono-delta-lacton" },
    use: { de: "Säureregulator", ru: "регулятор кислотности", pl: "regulator kwasowości", nl: "zuurteregelaar" },
    desc: { de: "Reguliert die Säure, in Tofu und verarbeitetem Fleisch. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Регулирует кислотность, в тофу и переработанном мясе. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Reguluje kwasowość, w tofu i przetworach mięsnych. Dozwolony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Regelt de zuurgraad, in tofu en bewerkt vlees. Toegelaten in de EU en door de EFSA als veilig beschouwd; wereldwijd toegestaan." },
  },
  "e620": {
    name: { de: "Glutaminsäure", ru: "Глутаминовая кислота", pl: "Kwas glutaminowy", nl: "Glutaminezuur" },
    use: { de: "Geschmacksverstärker", ru: "усилитель вкуса", pl: "wzmacniacz smaku", nl: "smaakversterker" },
    desc: { de: "Geschmacksverstärker, verwandt mit MSG. In der EU zugelassen, doch 2017 legte die EFSA erstmals eine tägliche Gruppenaufnahme für Glutamate fest, da die Exposition in einigen Gruppen den sicheren Wert überschreiten kann. Manche Menschen berichten von Empfindlichkeit. In Maßen.", ru: "Усилитель вкуса, родственный глутамату натрия (MSG). Разрешена в ЕС, но в 2017 году EFSA впервые установило групповую суточную дозу для глутаматов, поскольку воздействие в некоторых группах может превышать безопасный уровень. Некоторые отмечают чувствительность. Умеренно.", pl: "Wzmacniacz smaku, spokrewniony z MSG. Dozwolony w UE, ale w 2017 roku EFSA po raz pierwszy ustaliła grupowe dzienne spożycie dla glutaminianów, ponieważ ekspozycja może przekraczać bezpieczny poziom w niektórych grupach. Niektóre osoby zgłaszają nadwrażliwość. Z umiarem.", nl: "Smaakversterker, verwant aan MSG. Toegelaten in de EU, maar in 2017 stelde de EFSA voor het eerst een dagelijkse groepsinname voor glutamaten vast, omdat de blootstelling in sommige groepen het veilige niveau kan overschrijden. Sommigen melden gevoeligheid. Met mate." },
  },
  "e621": {
    name: { de: "Mononatriumglutamat (MSG)", ru: "Глутамат натрия (MSG)", pl: "Glutaminian monosodowy (MSG)", nl: "Mononatriumglutamaat (MSG)" },
    use: { de: "Geschmacksverstärker", ru: "усилитель вкуса", pl: "wzmacniacz smaku", nl: "smaakversterker" },
    desc: { de: "Geschmacksverstärker. In der EU zugelassen, doch 2017 legte die EFSA eine tägliche Gruppenaufnahme für Glutamate fest (30 mg/kg Körpergewicht) und stellte fest, dass die Exposition diese in einigen Gruppen überschreiten kann. Manche berichten von Empfindlichkeit (Kopfschmerzen). In Maßen.", ru: "Усилитель вкуса. Разрешён в ЕС, но в 2017 году EFSA установило групповую суточную дозу для глутаматов (30 мг/кг массы тела), отметив, что воздействие в некоторых группах может её превышать. Некоторые отмечают чувствительность (головные боли). Умеренно.", pl: "Wzmacniacz smaku. Dozwolony w UE, ale w 2017 roku EFSA ustaliła grupowe dzienne spożycie dla glutaminianów (30 mg/kg masy ciała), stwierdzając, że ekspozycja może je przekraczać w niektórych grupach. Niektóre osoby zgłaszają nadwrażliwość (bóle głowy). Z umiarem.", nl: "Smaakversterker. Toegelaten in de EU, maar in 2017 stelde de EFSA een dagelijkse groepsinname voor glutamaten vast (30 mg/kg lichaamsgewicht) en constateerde dat de blootstelling deze in sommige groepen kan overschrijden. Sommigen melden gevoeligheid (hoofdpijn). Met mate." },
  },
  "e627": {
    name: { de: "Dinatriumguanylat", ru: "Гуанилат динатрия", pl: "Guanylan disodowy", nl: "Dinatriumguanylaat" },
    use: { de: "Geschmacksverstärker", ru: "усилитель вкуса", pl: "wzmacniacz smaku", nl: "smaakversterker" },
    desc: { de: "Geschmacksverstärker, oft mit MSG kombiniert. In der EU zugelassen. Personen, die empfindlich auf Purine reagieren (Gicht), sollten vorsichtig sein. In Maßen.", ru: "Усилитель вкуса, часто сочетается с MSG. Разрешён в ЕС. Людям, чувствительным к пуринам (подагра), следует быть осторожными. Умеренно.", pl: "Wzmacniacz smaku, często łączony z MSG. Dozwolony w UE. Osoby wrażliwe na puryny (dna moczanowa) powinny zachować ostrożność. Z umiarem.", nl: "Smaakversterker, vaak gecombineerd met MSG. Toegelaten in de EU. Mensen die gevoelig zijn voor purines (jicht) moeten voorzichtig zijn. Met mate." },
  },
  "e631": {
    name: { de: "Dinatriuminosinat", ru: "Инозинат динатрия", pl: "Inozynian disodowy", nl: "Dinatriuminosinaat" },
    use: { de: "Geschmacksverstärker", ru: "усилитель вкуса", pl: "wzmacniacz smaku", nl: "smaakversterker" },
    desc: { de: "Geschmacksverstärker, oft mit MSG kombiniert. In der EU zugelassen. Vorsicht bei Personen mit Gicht. In Maßen.", ru: "Усилитель вкуса, часто сочетается с MSG. Разрешён в ЕС. Осторожность для людей с подагрой. Умеренно.", pl: "Wzmacniacz smaku, często łączony z MSG. Dozwolony w UE. Ostrożność u osób z dną moczanową. Z umiarem.", nl: "Smaakversterker, vaak gecombineerd met MSG. Toegelaten in de EU. Voorzichtigheid bij mensen met jicht. Met mate." },
  },
  "e635": {
    name: { de: "Dinatrium-5'-ribonukleotide", ru: "5'-рибонуклеотиды динатрия", pl: "Rybonukleotydy disodowe", nl: "Dinatrium-5'-ribonucleotiden" },
    use: { de: "Geschmacksverstärker", ru: "усилитель вкуса", pl: "wzmacniacz smaku", nl: "smaakversterker" },
    desc: { de: "Mischung aus Geschmacksverstärkern. In der EU zugelassen. Vorsicht bei Personen mit Gicht. In Maßen.", ru: "Смесь усилителей вкуса. Разрешена в ЕС. Осторожность для людей с подагрой. Умеренно.", pl: "Mieszanka wzmacniaczy smaku. Dozwolona w UE. Ostrożność u osób z dną moczanową. Z umiarem.", nl: "Mengsel van smaakversterkers. Toegelaten in de EU. Voorzichtigheid bij mensen met jicht. Met mate." },
  },
  "e640": {
    name: { de: "Glycin", ru: "Глицин", pl: "Glicyna", nl: "Glycine" },
    use: { de: "Geschmacksverstärker", ru: "усилитель вкуса", pl: "wzmacniacz smaku", nl: "smaakversterker" },
    desc: { de: "Aminosäure, die als Geschmacksverstärker verwendet wird. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Аминокислота, используемая как усилитель вкуса. Разрешена в ЕС и признана EFSA безопасной; разрешена во всём мире.", pl: "Aminokwas stosowany jako wzmacniacz smaku. Dopuszczona w UE i uznana przez EFSA za bezpieczną; dozwolona na całym świecie.", nl: "Aminozuur dat als smaakversterker wordt gebruikt. Toegelaten in de EU en door EFSA als veilig beoordeeld; wereldwijd toegestaan." },
  },
  "e901": {
    name: { de: "Bienenwachs", ru: "Пчелиный воск", pl: "Wosk pszczeli", nl: "Bijenwas" },
    use: { de: "Überzugsmittel", ru: "глазирователь", pl: "substancja glazurująca", nl: "glansmiddel" },
    desc: { de: "Natürliches Wachs für Glanz (Süßigkeiten, Obst). In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Натуральный воск для придания блеска (сладости, фрукты). Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Naturalny wosk nadający połysk (słodycze, owoce). Dopuszczony w UE i uznany przez EFSA za bezpieczny; dozwolony na całym świecie.", nl: "Natuurlijke was voor glans (snoep, fruit). Toegelaten in de EU en door EFSA als veilig beoordeeld; wereldwijd toegestaan." },
  },
  "e903": {
    name: { de: "Carnaubawachs", ru: "Карнаубский воск", pl: "Wosk carnauba", nl: "Carnaubawas" },
    use: { de: "Überzugsmittel", ru: "глазирователь", pl: "substancja glazurująca", nl: "glansmiddel" },
    desc: { de: "Pflanzliches Wachs für Glanz. In der EU innerhalb der von der EFSA festgelegten Grenzwerte zugelassen. Mäßigung.", ru: "Растительный воск для придания блеска. Разрешён в ЕС в пределах, установленных EFSA. Умеренность.", pl: "Wosk roślinny nadający połysk. Dopuszczony w UE w granicach ustalonych przez EFSA. Umiar.", nl: "Plantaardige was voor glans. Toegelaten in de EU binnen de door EFSA vastgestelde grenswaarden. Matiging." },
  },
  "e950": {
    name: { de: "Acesulfam K", ru: "Ацесульфам К", pl: "Acesulfam K", nl: "Acesulfaam K" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Künstlicher Süßstoff, oft mit Aspartam kombiniert. In der EU zugelassen und von der EFSA innerhalb des festgelegten Tageswerts als sicher eingestuft; weltweit erlaubt. Die EFSA bewertet das Aspartam-Acesulfam-Salz (E962) neu. Mäßigung.", ru: "Искусственный подсластитель, часто комбинируется с аспартамом. Разрешён в ЕС и признан EFSA безопасным в пределах установленной суточной нормы; разрешён во всём мире. EFSA проводит повторную оценку соли аспартам-ацесульфам (E962). Умеренность.", pl: "Sztuczna substancja słodząca, często łączona z aspartamem. Dopuszczony w UE i uznany przez EFSA za bezpieczny w granicach ustalonej dziennej dawki; dozwolony na całym świecie. EFSA ponownie ocenia sól aspartam-acesulfam (E962). Umiar.", nl: "Kunstmatige zoetstof, vaak gecombineerd met aspartaam. Toegelaten in de EU en door EFSA als veilig beoordeeld binnen de vastgestelde dagelijkse limiet; wereldwijd toegestaan. EFSA herbeoordeelt het aspartaam-acesulfaamzout (E962). Matiging." },
  },
  "e951": {
    name: { de: "Aspartam", ru: "Аспартам", pl: "Aspartam", nl: "Aspartaam" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Künstlicher Süßstoff. In der EU zugelassen; die EFSA hält an der zulässigen täglichen Aufnahme fest (40 mg/kg Körpergewicht, Bewertung 2013). 2023 stufte die WHO/IARC ihn auf der Grundlage begrenzter Hinweise als möglicherweise krebserregend (Gruppe 2B) ein, doch die WHO/JECFA behielt denselben sicheren Wert bei. In der EU müssen Produkte mit Aspartam den Hinweis \"enthält eine Phenylalaninquelle\" tragen (für Menschen mit Phenylketonurie). Vorsicht bei häufigem Gebrauch.", ru: "Искусственный подсластитель. Разрешён в ЕС; EFSA сохраняет допустимую суточную норму (40 мг/кг массы тела, оценка 2013 года). В 2023 году ВОЗ/IARC классифицировала его как возможно канцерогенный (группа 2B) на основании ограниченных данных, но ВОЗ/JECFA сохранила ту же безопасную норму. В ЕС продукты с аспартамом должны нести надпись \"содержит источник фенилаланина\" (для людей с фенилкетонурией). Осторожность при частом употреблении.", pl: "Sztuczna substancja słodząca. Dopuszczony w UE; EFSA utrzymuje dopuszczalne dzienne spożycie (40 mg/kg masy ciała, ocena z 2013 r.). W 2023 r. WHO/IARC sklasyfikowała go jako możliwie rakotwórczy (grupa 2B) na podstawie ograniczonych dowodów, ale WHO/JECFA utrzymała tę samą bezpieczną dawkę. W UE produkty z aspartamem muszą zawierać oznaczenie \"zawiera źródło fenyloalaniny\" (dla osób z fenyloketonurią). Ostrożność przy częstym stosowaniu.", nl: "Kunstmatige zoetstof. Toegelaten in de EU; EFSA handhaaft de aanvaardbare dagelijkse inname (40 mg/kg lichaamsgewicht, beoordeling 2013). In 2023 classificeerde de WHO/IARC het als mogelijk kankerverwekkend (groep 2B) op basis van beperkt bewijs, maar de WHO/JECFA behield dezelfde veilige dosis. In de EU moeten producten met aspartaam de vermelding \"bevat een bron van fenylalanine\" dragen (voor mensen met fenylketonurie). Voorzichtigheid bij frequent gebruik." },
  },
  "e952": {
    name: { de: "Cyclamat", ru: "Цикламат", pl: "Cyklaminian", nl: "Cyclamaat" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Künstlicher Süßstoff. In der EU mit Grenzwerten zugelassen, aber in den USA seit 1970 aufgrund älterer Studien VERBOTEN. Vorsicht bei häufigem Gebrauch.", ru: "Искусственный подсластитель. Разрешён в ЕС с ограничениями, но ЗАПРЕЩЁН в США с 1970 года из-за старых исследований. Осторожность при частом употреблении.", pl: "Sztuczna substancja słodząca. Dopuszczony w UE z ograniczeniami, ale ZAKAZANY w USA od 1970 r. z powodu dawnych badań. Ostrożność przy częstym stosowaniu.", nl: "Kunstmatige zoetstof. Toegelaten in de EU met grenswaarden, maar in de VS sinds 1970 VERBODEN vanwege oudere studies. Voorzichtigheid bij frequent gebruik." },
  },
  "e954": {
    name: { de: "Saccharin", ru: "Сахарин", pl: "Sacharyna", nl: "Sacharine" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Einer der ältesten künstlichen Süßstoffe. In der EU mit von der EFSA festgelegten Grenzwerten zugelassen. Alte Rattenstudien weckten Bedenken (beim Menschen nicht bestätigt; die USA zogen ihren Warnhinweis 2000 zurück). Vorsicht.", ru: "Один из старейших искусственных подсластителей. Разрешён в ЕС с ограничениями, установленными EFSA. Старые исследования на крысах вызвали опасения (не подтверждённые у людей; США отозвали своё предупреждение в 2000 году). Осторожность.", pl: "Jedna z najstarszych sztucznych substancji słodzących. Dopuszczona w UE z ograniczeniami ustalonymi przez EFSA. Dawne badania na szczurach wzbudziły obawy (niepotwierdzone u ludzi; USA wycofały ostrzeżenie w 2000 r.). Ostrożność.", nl: "Een van de oudste kunstmatige zoetstoffen. Toegelaten in de EU met door EFSA vastgestelde grenswaarden. Oude rattenstudies wekten zorgen (niet bevestigd bij mensen; de VS trok zijn waarschuwing in 2000 in). Voorzichtigheid." },
  },
  "e955": {
    name: { de: "Sucralose", ru: "Сукралоза", pl: "Sukraloza", nl: "Sucralose" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Kalorienfreier künstlicher Süßstoff. In der EU zugelassen und von der EFSA innerhalb des Tageswerts als sicher eingestuft; weltweit erlaubt. Neuere Studien untersuchen Auswirkungen auf die Darmflora und beim Erhitzen (nicht zum Kochen bei hohen Temperaturen empfohlen). Mäßigung.", ru: "Бескалорийный искусственный подсластитель. Разрешён в ЕС и признан EFSA безопасным в пределах суточной нормы; разрешён во всём мире. Недавние исследования изучают влияние на кишечную микрофлору и при нагревании (не рекомендуется для готовки при высоких температурах). Умеренность.", pl: "Bezkaloryczna sztuczna substancja słodząca. Dopuszczona w UE i uznana przez EFSA za bezpieczną w granicach dziennej dawki; dozwolona na całym świecie. Najnowsze badania analizują wpływ na florę jelitową oraz przy podgrzewaniu (niezalecana do gotowania w wysokich temperaturach). Umiar.", nl: "Calorievrije kunstmatige zoetstof. Toegelaten in de EU en door EFSA als veilig beoordeeld binnen de dagelijkse limiet; wereldwijd toegestaan. Recente studies onderzoeken effecten op de darmflora en bij verhitting (niet aanbevolen om op hoge temperatuur te koken). Matiging." },
  },
  "e960": {
    name: { de: "Steviolglycoside (Stevia)", ru: "Стевиолгликозиды (Стевия)", pl: "Glikozydy stewiolowe (Stevia)", nl: "Steviolglycosiden (Stevia)" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Natürlicher kalorienfreier Süßstoff aus der Stevia-Pflanze. In der EU seit 2011 zugelassen und von der EFSA innerhalb des Tageswerts als sicher eingestuft; weltweit erlaubt. Eine bessere Wahl als künstliche Süßstoffe.", ru: "Натуральный бескалорийный подсластитель из растения стевия. Разрешён в ЕС с 2011 года и признан EFSA безопасным в пределах суточной нормы; разрешён во всём мире. Более удачный выбор, чем искусственные подсластители.", pl: "Naturalna bezkaloryczna substancja słodząca z rośliny stewia. Dopuszczona w UE od 2011 r. i uznana przez EFSA za bezpieczną w granicach dziennej dawki; dozwolona na całym świecie. Lepszy wybór niż sztuczne substancje słodzące.", nl: "Natuurlijke calorievrije zoetstof uit de steviaplant. Sinds 2011 toegelaten in de EU en door EFSA als veilig beoordeeld binnen de dagelijkse limiet; wereldwijd toegestaan. Een betere keuze dan kunstmatige zoetstoffen." },
  },
  "e965": {
    name: { de: "Maltit", ru: "Мальтит", pl: "Maltitol", nl: "Maltitol" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Kalorienärmerer Zuckeralkohol-Süßstoff. In der EU zugelassen und von der EFSA als sicher eingestuft, doch die EU verlangt den Hinweis \"kann bei übermäßigem Verzehr abführend wirken\". Mäßigung.", ru: "Подсластитель-полиол с пониженной калорийностью. Разрешён в ЕС и признан EFSA безопасным, но ЕС требует надписи \"чрезмерное употребление может оказывать слабительное действие\". Умеренность.", pl: "Substancja słodząca z grupy polioli o obniżonej kaloryczności. Dopuszczona w UE i uznana przez EFSA za bezpieczną, lecz UE wymaga oznaczenia \"nadmierne spożycie może mieć działanie przeczyszczające\". Umiar.", nl: "Polyolzoetstof met minder calorieën. Toegelaten in de EU en door EFSA als veilig beoordeeld, maar de EU vereist de vermelding \"overmatig gebruik kan een laxerend effect hebben\". Matiging." },
  },
  "e967": {
    name: { de: "Xylit", ru: "Ксилит", pl: "Ksylitol", nl: "Xylitol" },
    use: { de: "Süßungsmittel", ru: "подсластитель", pl: "substancja słodząca", nl: "zoetstof" },
    desc: { de: "Natürlicher Süßstoff, gut für die Zähne. In der EU zugelassen und von der EFSA als sicher eingestuft, doch die EU verlangt den Hinweis auf die abführende Wirkung. Achtung: hochgiftig für Hunde.", ru: "Натуральный подсластитель, полезный для зубов. Разрешён в ЕС и признан EFSA безопасным, но ЕС требует надписи о слабительном действии. Внимание: очень токсичен для собак.", pl: "Naturalna substancja słodząca, korzystna dla zębów. Dopuszczona w UE i uznana przez EFSA za bezpieczną, lecz UE wymaga oznaczenia o działaniu przeczyszczającym. Uwaga: bardzo toksyczny dla psów.", nl: "Natuurlijke zoetstof, goed voor de tanden. Toegelaten in de EU en door EFSA als veilig beoordeeld, maar de EU vereist de vermelding over het laxerende effect. Let op: zeer giftig voor honden." },
  },
  "e1442": {
    name: { de: "Modifizierte Stärke", ru: "Модифицированный крахмал", pl: "Skrobia modyfikowana", nl: "Gemodificeerd zetmeel" },
    use: { de: "Stabilisator", ru: "стабилизатор", pl: "stabilizator", nl: "stabilisator" },
    desc: { de: "Stärke, die zum Verdicken und Stabilisieren behandelt wurde. In der EU zugelassen und von der EFSA als sicher eingestuft; weltweit erlaubt.", ru: "Крахмал, обработанный для загущения и стабилизации. Разрешён в ЕС и признан EFSA безопасным; разрешён во всём мире.", pl: "Skrobia poddana obróbce w celu zagęszczania i stabilizacji. Dopuszczona w UE i uznana przez EFSA za bezpieczną; dozwolona na całym świecie.", nl: "Zetmeel dat is behandeld om te verdikken en te stabiliseren. Toegelaten in de EU en door EFSA als veilig beoordeeld; wereldwijd toegestaan." },
  },
  "e1510": {
    name: { de: "Ethanol (Alkohol)", ru: "Этанол (спирт)", pl: "Etanol (alkohol)", nl: "Ethanol (alcohol)" },
    use: { de: "Lösungsmittel", ru: "растворитель", pl: "rozpuszczalnik", nl: "oplosmiddel" },
    desc: { de: "Wird als Lösungsmittel für Aromen verwendet. In der EU zugelassen; in den in Lebensmitteln vorhandenen Restmengen sicher.", ru: "Используется как растворитель для ароматизаторов. Разрешён в ЕС; безопасен в остаточных количествах, присутствующих в пище.", pl: "Stosowany jako rozpuszczalnik dla aromatów. Dopuszczony w UE; bezpieczny w ilościach śladowych występujących w żywności.", nl: "Gebruikt als oplosmiddel voor aroma's. Toegelaten in de EU; veilig in de resthoeveelheden die in voedsel voorkomen." },
  },
};
