// AUTO-GENERAT — traduceri DE/RU/PL/NL pentru substante cosmetice (INCI).
// Se imbina automat in fisierul principal (vezi merge-ul de la finalul acelui fisier).
// Pentru a edita o limba existenta (ro/en/fr/it/es) modifica fisierul principal.
export const cosmeticsExtra: Record<string, { name: any; use: any; desc: any }> = {
  "methylparaben": {
    name: { de: "Methylparaben", ru: "Метилпарабен", pl: "Metyloparaben", nl: "Methylparabeen" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff aus der Familie der Parabene. In der EU bis 0,4 % zugelassen (Verordnung 1223/2009), vom SCCS als einer der sichersten Parabene eingestuft. Dennoch stehen Parabene im Verdacht, das Hormonsystem (endokrin) zu stören, und viele vermeiden sie lieber. In Maßen.", ru: "Консервант из группы парабенов. Разрешён в ЕС до 0,4 % (Рег. 1223/2009), SCCS считает его одним из самых безопасных парабенов. Тем не менее парабены подозреваются в нарушении работы эндокринной (гормональной) системы, и многие предпочитают их избегать. Умеренность.", pl: "Konserwant z rodziny parabenów. Dozwolony w UE do 0,4 % (Rozp. 1223/2009), uznawany przez SCCS za jeden z najbezpieczniejszych parabenów. Mimo to parabeny są podejrzewane o zaburzanie układu hormonalnego (endokrynnego) i wiele osób woli ich unikać. Z umiarem.", nl: "Conserveermiddel uit de parabenenfamilie. In de EU toegestaan tot 0,4 % (Verord. 1223/2009), door het SCCS beschouwd als een van de veiligste parabenen. Toch worden parabenen verdacht van hormoonverstoring (endocrien) en velen vermijden ze liever. Met mate." },
  },
  "ethylparaben": {
    name: { de: "Ethylparaben", ru: "Этилпарабен", pl: "Etyloparaben", nl: "Ethylparabeen" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff aus der Familie der Parabene. In der EU bis 0,4 % zugelassen und vom SCCS als einer der sichersten eingestuft. Parabene stehen im Verdacht, das Hormonsystem zu stören; viele vermeiden sie lieber. In Maßen.", ru: "Консервант из группы парабенов. Разрешён в ЕС до 0,4 % и считается SCCS одним из самых безопасных. Парабены подозреваются в гормональных нарушениях; многие предпочитают их избегать. Умеренность.", pl: "Konserwant z rodziny parabenów. Dozwolony w UE do 0,4 % i uznawany przez SCCS za jeden z najbezpieczniejszych. Parabeny są podejrzewane o zaburzanie gospodarki hormonalnej; wiele osób woli ich unikać. Z umiarem.", nl: "Conserveermiddel uit de parabenenfamilie. In de EU toegestaan tot 0,4 % en door het SCCS beschouwd als een van de veiligste. Parabenen worden verdacht van hormoonverstoring; velen vermijden ze liever. Met mate." },
  },
  "propylparaben": {
    name: { de: "Propylparaben", ru: "Пропилпарабен", pl: "Propyloparaben", nl: "Propylparabeen" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Paraben mit längerer Kette. In der EU auf 0,14 % beschränkt und im Windelbereich bei Kindern unter 3 Jahren VERBOTEN, wegen Verdacht auf endokrine Störung. Vorsicht.", ru: "Парабен с более длинной цепью. В ЕС ограничен до 0,14 % и ЗАПРЕЩЁН в средствах для области подгузника у детей до 3 лет из-за подозрения на нарушение эндокринной системы. Осторожно.", pl: "Paraben o dłuższym łańcuchu. Ograniczony w UE do 0,14 % i ZAKAZANY w produktach do okolicy pieluszkowej u dzieci poniżej 3 lat, z powodu podejrzenia zaburzeń endokrynnych. Ostrożnie.", nl: "Paraben met langere keten. In de EU beperkt tot 0,14 % en VERBODEN in producten voor het luiergebied bij kinderen onder de 3 jaar, wegens verdenking van hormoonverstoring. Voorzichtigheid." },
  },
  "butylparaben": {
    name: { de: "Butylparaben", ru: "Бутилпарабен", pl: "Butyloparaben", nl: "Butylparabeen" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Paraben mit langer Kette. In der EU auf 0,14 % beschränkt und im Windelbereich bei Kindern unter 3 Jahren VERBOTEN. Verdacht auf endokrine (hormonelle) Störung. Vorsicht.", ru: "Парабен с длинной цепью. В ЕС ограничен до 0,14 % и ЗАПРЕЩЁН в средствах для области подгузника у детей до 3 лет. Подозревается в нарушении эндокринной (гормональной) системы. Осторожно.", pl: "Paraben o długim łańcuchu. Ograniczony w UE do 0,14 % i ZAKAZANY w produktach do okolicy pieluszkowej u dzieci poniżej 3 lat. Podejrzewany o zaburzenia endokrynne (hormonalne). Ostrożnie.", nl: "Paraben met lange keten. In de EU beperkt tot 0,14 % en VERBODEN in producten voor het luiergebied bij kinderen onder de 3 jaar. Verdacht van hormoonverstoring (endocrien). Voorzichtigheid." },
  },
  "isobutylparaben": {
    name: { de: "Isobutylparaben", ru: "Изобутилпарабен", pl: "Izobutyloparaben", nl: "Isobutylparabeen" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Paraben, in der EU seit 2014 VERBOTEN (Verordnung 358/2014), wegen fehlender Daten zur Sicherheitsbestätigung und Verdacht auf endokrine Störung. Erscheint es auf dem Etikett, ist das Produkt alt oder nicht konform. Vermeiden.", ru: "Парабен, ЗАПРЕЩЁН в ЕС с 2014 года (Рег. 358/2014) из-за отсутствия данных, подтверждающих безопасность, и подозрения на нарушение эндокринной системы. Если он указан на этикетке, продукт старый или не соответствует нормам. Избегайте.", pl: "Paraben ZAKAZANY w UE od 2014 roku (Rozp. 358/2014) z powodu braku danych potwierdzających bezpieczeństwo i podejrzenia zaburzeń endokrynnych. Jeśli pojawia się na etykiecie, produkt jest stary lub niezgodny z przepisami. Unikaj.", nl: "Paraben, in de EU sinds 2014 VERBODEN (Verord. 358/2014), wegens gebrek aan gegevens die de veiligheid bevestigen en verdenking van hormoonverstoring. Staat het op het etiket, dan is het product oud of niet conform. Vermijden." },
  },
  "phenoxyethanol": {
    name: { de: "Phenoxyethanol", ru: "Феноксиэтанол", pl: "Fenoksyetanol", nl: "Fenoxyethanol" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Sehr verbreiteter Konservierungsstoff. In der EU bis 1 % zugelassen und vom SCCS bei dieser Grenze als sicher eingestuft. Kann empfindliche Haut reizen; einige Länder raten bei Babyprodukten zur Vorsicht. In Maßen.", ru: "Очень распространённый консервант. Разрешён в ЕС до 1 % и считается SCCS безопасным при этом пределе. Может раздражать чувствительную кожу; некоторые страны советуют осторожность в детских средствах. Умеренность.", pl: "Bardzo rozpowszechniony konserwant. Dozwolony w UE do 1 % i uznawany przez SCCS za bezpieczny przy tym limicie. Może podrażniać wrażliwą skórę; niektóre kraje zalecają ostrożność w produktach dla niemowląt. Z umiarem.", nl: "Zeer veelvoorkomend conserveermiddel. In de EU toegestaan tot 1 % en door het SCCS bij deze grens als veilig beschouwd. Kan gevoelige huid irriteren; sommige landen adviseren voorzichtigheid bij babyproducten. Met mate." },
  },
  "formaldehyde": {
    name: { de: "Formaldehyd", ru: "Формальдегид", pl: "Formaldehyd", nl: "Formaldehyde" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff, von der EU als krebserregend (CMR) und als Allergen eingestuft. Der direkte Zusatz von freiem Formaldehyd in Kosmetika ist in der EU VERBOTEN; Produkte, die mehr als 0,001 % freisetzen, müssen den Hinweis \"setzt Formaldehyd frei\" tragen. In den USA innerhalb von Grenzwerten noch erlaubt. Vermeiden.", ru: "Консервант, классифицированный ЕС как канцероген (CMR) и аллерген. Прямое добавление свободного формальдегида в косметику ЗАПРЕЩЕНО в ЕС; продукты, выделяющие более 0,001 %, должны иметь предупреждение \"выделяет формальдегид\". В США всё ещё разрешён в пределах норм. Избегайте.", pl: "Konserwant sklasyfikowany przez UE jako rakotwórczy (CMR) i alergen. Bezpośrednie dodawanie wolnego formaldehydu do kosmetyków jest w UE ZAKAZANE; produkty uwalniające ponad 0,001 % muszą zawierać ostrzeżenie \"uwalnia formaldehyd\". W USA nadal dozwolony w granicach norm. Unikaj.", nl: "Conserveermiddel, door de EU geclassificeerd als kankerverwekkend (CMR) en als allergeen. Het rechtstreeks toevoegen van vrij formaldehyde aan cosmetica is in de EU VERBODEN; producten die meer dan 0,001 % vrijgeven moeten de waarschuwing \"geeft formaldehyde af\" dragen. In de VS binnen grenzen nog toegestaan. Vermijden." },
  },
  "dmdm hydantoin": {
    name: { de: "DMDM-Hydantoin", ru: "ДМДМ-гидантоин", pl: "DMDM hydantoina", nl: "DMDM-hydantoïne" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff, der langsam Formaldehyd (ein Karzinogen) freisetzt. In der EU innerhalb von Grenzwerten zugelassen, aber Produkte, die über dem Schwellenwert freisetzen, müssen einen Warnhinweis tragen. Menschen mit Formaldehydallergie sollten ihn meiden. Vorsicht.", ru: "Консервант, медленно выделяющий формальдегид (канцероген). Разрешён в ЕС в пределах норм, но продукты, выделяющие выше порога, должны иметь предупреждение. Людям с аллергией на формальдегид следует его избегать. Осторожно.", pl: "Konserwant, który powoli uwalnia formaldehyd (substancję rakotwórczą). Dozwolony w UE w granicach norm, ale produkty uwalniające powyżej progu muszą zawierać ostrzeżenie. Osoby uczulone na formaldehyd powinny go unikać. Ostrożnie.", nl: "Conserveermiddel dat langzaam formaldehyde (een kankerverwekkende stof) afgeeft. In de EU binnen grenzen toegestaan, maar producten die boven de drempel afgeven moeten een waarschuwing dragen. Mensen met een formaldehyde-allergie moeten het vermijden. Voorzichtigheid." },
  },
  "imidazolidinyl urea": {
    name: { de: "Imidazolidinylharnstoff", ru: "Имидазолидинилмочевина", pl: "Imidazolidynylomocznik", nl: "Imidazolidinylureum" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Formaldehyd freisetzender Konservierungsstoff. In der EU innerhalb von Grenzwerten zugelassen, mit verpflichtendem Warnhinweis oberhalb des Schwellenwerts. Kann Kontaktallergien auslösen. Vorsicht.", ru: "Консервант, выделяющий формальдегид. Разрешён в ЕС в пределах норм, с обязательным предупреждением выше порога. Может вызывать контактную аллергию. Осторожно.", pl: "Konserwant uwalniający formaldehyd. Dozwolony w UE w granicach norm, z obowiązkowym ostrzeżeniem powyżej progu. Może powodować alergie kontaktowe. Ostrożnie.", nl: "Formaldehyde afgevend conserveermiddel. In de EU binnen grenzen toegestaan, met verplichte waarschuwing boven de drempel. Kan contactallergieën veroorzaken. Voorzichtigheid." },
  },
  "diazolidinyl urea": {
    name: { de: "Diazolidinylharnstoff", ru: "Диазолидинилмочевина", pl: "Diazolidynylomocznik", nl: "Diazolidinylureum" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Formaldehyd freisetzender Konservierungsstoff. In der EU innerhalb von Grenzwerten zugelassen, mit verpflichtendem Warnhinweis oberhalb des Schwellenwerts. Mögliche Kontaktallergien. Vorsicht.", ru: "Консервант, выделяющий формальдегид. Разрешён в ЕС в пределах норм, с обязательным предупреждением выше порога. Возможны контактные аллергии. Осторожно.", pl: "Konserwant uwalniający formaldehyd. Dozwolony w UE w granicach norm, z obowiązkowym ostrzeżeniem powyżej progu. Możliwe alergie kontaktowe. Ostrożnie.", nl: "Formaldehyde afgevend conserveermiddel. In de EU binnen grenzen toegestaan, met verplichte waarschuwing boven de drempel. Mogelijke contactallergieën. Voorzichtigheid." },
  },
  "methylisothiazolinone": {
    name: { de: "Methylisothiazolinon (MIT)", ru: "Метилизотиазолинон (MIT)", pl: "Metyloizotiazolinon (MIT)", nl: "Methylisothiazolinon (MIT)" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Konservierungsstoff, der in Europa eine Epidemie von Kontaktallergien ausgelöst hat. Die EU hat ihn in Leave-on-Produkten VERBOTEN und in Rinse-off-Produkten streng beschränkt. Ein starkes Allergen. Vorsicht.", ru: "Консервант, вызвавший в Европе эпидемию контактной аллергии. ЕС ЗАПРЕТИЛ его в несмываемых средствах (leave-on) и строго ограничил в смываемых. Сильный аллерген. Осторожно.", pl: "Konserwant, który wywołał w Europie epidemię alergii kontaktowych. UE ZAKAZAŁA go w produktach niespłukiwanych (leave-on) i ściśle ograniczyła w spłukiwanych. Silny alergen. Ostrożnie.", nl: "Conserveermiddel dat in Europa een epidemie van contactallergieën veroorzaakte. De EU heeft het VERBODEN in leave-onproducten en streng beperkt in afspoelbare producten. Een sterk allergeen. Voorzichtigheid." },
  },
  "methylchloroisothiazolinone": {
    name: { de: "Methylchlorisothiazolinon (CMIT)", ru: "Метилхлоризотиазолинон (CMIT)", pl: "Metylochloroizotiazolinon (CMIT)", nl: "Methylchloorisothiazolinon (CMIT)" },
    use: { de: "Konservierungsstoff", ru: "консервант", pl: "konserwant", nl: "conserveermiddel" },
    desc: { de: "Stark allergener Konservierungsstoff, oft mit MIT kombiniert. In der EU nur in Rinse-off-Produkten in sehr geringer Konzentration zugelassen. In Leave-on-Produkten verboten. Vorsicht.", ru: "Сильный аллергенный консервант, часто в сочетании с MIT. Разрешён в ЕС только в смываемых средствах в очень низкой концентрации. Запрещён в несмываемых средствах. Осторожно.", pl: "Silnie alergizujący konserwant, często łączony z MIT. Dozwolony w UE tylko w produktach spłukiwanych, w bardzo niskim stężeniu. Zakazany w produktach niespłukiwanych. Ostrożnie.", nl: "Sterk allergeen conserveermiddel, vaak gecombineerd met MIT. In de EU alleen toegestaan in afspoelbare producten in zeer lage concentratie. Verboden in leave-onproducten. Voorzichtigheid." },
  },
  "triclosan": {
    name: { de: "Triclosan", ru: "Триклозан", pl: "Triklosan", nl: "Triclosan" },
    use: { de: "antibakterieller Konservierungsstoff", ru: "антибактериальный консервант", pl: "konserwant antybakteryjny", nl: "antibacterieel conserveermiddel" },
    desc: { de: "Antibakterieller Wirkstoff, der mit Antibiotikaresistenz und endokriner Störung in Verbindung gebracht wird. Die EU hat ihn stark beschränkt und in vielen Produkten verboten; seine Verwendung ist sehr begrenzt. In Seifen in den USA seit 2016 verboten. Vermeiden.", ru: "Антибактериальный агент, связанный с устойчивостью к антибиотикам и нарушением эндокринной системы. ЕС строго ограничил его и запретил во многих продуктах; его применение очень ограничено. Запрещён в мыле в США с 2016 года. Избегайте.", pl: "Środek antybakteryjny powiązany z opornością na antybiotyki i zaburzeniami endokrynnymi. UE silnie go ograniczyła i zakazała w wielu produktach; jego stosowanie jest bardzo ograniczone. Zakazany w mydłach w USA od 2016 roku. Unikaj.", nl: "Antibacterieel middel dat in verband wordt gebracht met antibioticaresistentie en hormoonverstoring. De EU heeft het sterk beperkt en in veel producten verboden; het gebruik is zeer beperkt. In zepen in de VS sinds 2016 verboden. Vermijden." },
  },
  "hydroquinone": {
    name: { de: "Hydrochinon", ru: "Гидрохинон", pl: "Hydrochinon", nl: "Hydrochinon" },
    use: { de: "Hautaufhellungsmittel", ru: "осветляющее средство", pl: "środek wybielający skórę", nl: "huidblekend middel" },
    desc: { de: "Hautaufhellende Substanz. In EU-Kosmetika VERBOTEN (nur auf ärztliche Verschreibung erlaubt). Verdacht auf krebserregende Wirkung in Tierstudien. In den USA in rezeptfreien Produkten verboten. Vermeiden.", ru: "Осветляющее кожу вещество. ЗАПРЕЩЕНО в косметике ЕС (разрешено только по рецепту врача). Подозревается в канцерогенном действии по результатам исследований на животных. В США запрещено в безрецептурных средствах. Избегайте.", pl: "Substancja wybielająca skórę. ZAKAZANA w kosmetykach UE (dozwolona tylko na receptę lekarską). Podejrzewana o działanie rakotwórcze w badaniach na zwierzętach. W USA zakazana w produktach dostępnych bez recepty. Unikaj.", nl: "Huidblekende stof. VERBODEN in EU-cosmetica (alleen toegestaan op medisch voorschrift). Verdacht van kankerverwekkende effecten in dierstudies. In de VS verboden in vrij verkrijgbare producten. Vermijden." },
  },
  "sodium lauryl sulfate": {
    name: { de: "Natriumlaurylsulfat (SLS)", ru: "Лаурилсульфат натрия (SLS)", pl: "Laurylosiarczan sodu (SLS)", nl: "Natriumlaurylsulfaat (SLS)" },
    use: { de: "Schaumbildner", ru: "пенообразователь", pl: "środek pieniący", nl: "schuimmiddel" },
    desc: { de: "Schaumbildendes Tensid in Shampoos und Gels. In der EU zugelassen und als sicher eingestuft, kann aber Haut und Augen reizen, besonders bei empfindlichen Personen oder hohen Konzentrationen. Nicht giftig, nur reizend. In Maßen.", ru: "Пенящееся моющее вещество в шампунях и гелях. Разрешён в ЕС и считается безопасным, но может раздражать кожу и глаза, особенно у чувствительных людей или при высоких концентрациях. Не токсичен, лишь раздражает. Умеренность.", pl: "Pieniący detergent w szamponach i żelach. Dozwolony w UE i uznawany za bezpieczny, ale może podrażniać skórę i oczy, zwłaszcza u osób wrażliwych lub przy wysokich stężeniach. Nietoksyczny, jedynie drażniący. Z umiarem.", nl: "Schuimend reinigingsmiddel in shampoos en gels. In de EU toegestaan en als veilig beschouwd, maar kan huid en ogen irriteren, vooral bij gevoelige personen of hoge concentraties. Niet giftig, alleen irriterend. Met mate." },
  },
  "sodium laureth sulfate": {
    name: { de: "Natriumlaurethsulfat (SLES)", ru: "Лаурет сульфат натрия (SLES)", pl: "Sól sodowa siarczanu laurylowo-eterowego (SLES)", nl: "Natriumlaurethsulfaat (SLES)" },
    use: { de: "Schaumbildner", ru: "пенообразователь", pl: "środek pieniący", nl: "schuimmiddel" },
    desc: { de: "Milderes Tensid als SLS. In der EU zugelassen und als sicher eingestuft, jedoch weniger reizend. Mögliche Verunreinigung mit Spuren von 1,4-Dioxan aus der Herstellung (Hersteller reduzieren sie). Mäßigung.", ru: "Более мягкое моющее вещество, чем SLS. Разрешён в ЕС и считается безопасным, но менее раздражающим. Возможно загрязнение следами 1,4-диоксана при производстве (производители его снижают). Умеренность.", pl: "Łagodniejszy detergent niż SLS. Dozwolony w UE i uznany za bezpieczny, ale mniej drażniący. Możliwe zanieczyszczenie śladami 1,4-dioksanu z produkcji (producenci je ograniczają). Umiar.", nl: "Mildere detergent dan SLS. Toegestaan in de EU en als veilig beschouwd, maar minder irriterend. Mogelijke verontreiniging met sporen van 1,4-dioxaan uit de productie (fabrikanten beperken dit). Matiging." },
  },
  "cocamidopropyl betaine": {
    name: { de: "Cocamidopropylbetain", ru: "Кокамидопропилбетаин", pl: "Kokamidopropylobetaina", nl: "Cocamidopropylbetaïne" },
    use: { de: "Schaumbildner", ru: "пенообразователь", pl: "środek pieniący", nl: "schuimmiddel" },
    desc: { de: "Mildes Tensid aus Kokosnuss. In der EU zugelassen und als sicher eingestuft. Kann aufgrund von Verunreinigungen aus der Herstellung Kontaktallergien auslösen. Mäßigung.", ru: "Мягкое моющее вещество, получаемое из кокоса. Разрешён в ЕС и считается безопасным. Может вызывать контактную аллергию из-за примесей при производстве. Умеренность.", pl: "Łagodny detergent pozyskiwany z kokosa. Dozwolony w UE i uznany za bezpieczny. Może powodować alergie kontaktowe z powodu zanieczyszczeń produkcyjnych. Umiar.", nl: "Mild detergent afgeleid van kokos. Toegestaan in de EU en als veilig beschouwd. Kan contactallergieën veroorzaken door onzuiverheden uit de productie. Matiging." },
  },
  "limonene": {
    name: { de: "Limonen", ru: "Лимонен", pl: "Limonen", nl: "Limoneen" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Sehr verbreiteter Duftstoffbestandteil mit Zitrusduft. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU (Reg. 1223/2009). Durch Oxidation an der Luft wird er zu einem stärkeren Allergen. Vorsicht bei empfindlichen Personen.", ru: "Очень распространённый компонент отдушки с цитрусовым запахом. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС (Reg. 1223/2009). При окислении на воздухе становится более сильным аллергеном. Осторожность для чувствительных людей.", pl: "Bardzo rozpowszechniony składnik zapachowy o cytrusowym aromacie. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE (Reg. 1223/2009). Pod wpływem utleniania na powietrzu staje się silniejszym alergenem. Ostrożność u osób wrażliwych.", nl: "Zeer veelvoorkomend geurbestanddeel met citrusgeur. Een van de 26 geurallergenen met verplichte etikettering in de EU (Reg. 1223/2009). Door oxidatie aan de lucht wordt het een sterker allergeen. Voorzichtigheid bij gevoelige personen." },
  },
  "linalool": {
    name: { de: "Linalool", ru: "Линалоол", pl: "Linalol", nl: "Linalool" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Sehr verbreiteter Duftstoffbestandteil mit blumigem Duft (in 85-90 % der Produkte). Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. An der Luft oxidiert wird er zu einem stärkeren Allergen. Vorsicht bei empfindlichen Personen.", ru: "Очень распространённый компонент отдушки с цветочным запахом (присутствует в 85-90 % продуктов). Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Окисляясь на воздухе, становится более сильным аллергеном. Осторожность для чувствительных людей.", pl: "Bardzo rozpowszechniony składnik zapachowy o kwiatowym aromacie (obecny w 85-90 % produktów). Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Utleniony na powietrzu staje się silniejszym alergenem. Ostrożność u osób wrażliwych.", nl: "Zeer veelvoorkomend geurbestanddeel met bloemige geur (in 85-90 % van de producten). Een van de 26 geurallergenen met verplichte etikettering in de EU. Door oxidatie aan de lucht wordt het een sterker allergeen. Voorzichtigheid bij gevoelige personen." },
  },
  "citronellol": {
    name: { de: "Citronellol", ru: "Цитронеллол", pl: "Cytronelol", nl: "Citronellol" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Blumiger Duftstoffbestandteil. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. Kann bei empfindlichen Personen Kontaktallergien auslösen. Vorsicht.", ru: "Компонент отдушки с цветочным запахом. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Может вызывать контактную аллергию у чувствительных людей. Осторожность.", pl: "Kwiatowy składnik zapachowy. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Może powodować alergie kontaktowe u osób wrażliwych. Ostrożność.", nl: "Bloemig geurbestanddeel. Een van de 26 geurallergenen met verplichte etikettering in de EU. Kan bij gevoelige personen contactallergieën veroorzaken. Voorzichtigheid." },
  },
  "geraniol": {
    name: { de: "Geraniol", ru: "Гераниол", pl: "Geraniol", nl: "Geraniol" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Duftstoffbestandteil mit Rosenduft. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. Kann Kontaktallergien auslösen. Vorsicht bei empfindlichen Personen.", ru: "Компонент отдушки с запахом розы. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Может вызывать контактную аллергию. Осторожность для чувствительных людей.", pl: "Składnik zapachowy o zapachu róży. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Może powodować alergie kontaktowe. Ostrożność u osób wrażliwych.", nl: "Geurbestanddeel met rozengeur. Een van de 26 geurallergenen met verplichte etikettering in de EU. Kan contactallergieën veroorzaken. Voorzichtigheid bij gevoelige personen." },
  },
  "eugenol": {
    name: { de: "Eugenol", ru: "Эвгенол", pl: "Eugenol", nl: "Eugenol" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Duftstoffbestandteil mit Nelkenduft. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. Bekanntes Kontaktallergen. Vorsicht bei empfindlichen Personen.", ru: "Компонент отдушки с запахом гвоздики. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Известный контактный аллерген. Осторожность для чувствительных людей.", pl: "Składnik zapachowy o zapachu goździków. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Znany alergen kontaktowy. Ostrożność u osób wrażliwych.", nl: "Geurbestanddeel met kruidnagelgeur. Een van de 26 geurallergenen met verplichte etikettering in de EU. Bekend contactallergeen. Voorzichtigheid bij gevoelige personen." },
  },
  "coumarin": {
    name: { de: "Cumarin", ru: "Кумарин", pl: "Kumaryna", nl: "Cumarine" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Duftstoffbestandteil mit Vanille-/Heuduft. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. Kann Kontaktallergien auslösen. Vorsicht.", ru: "Компонент отдушки с запахом ванили/сена. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Может вызывать контактную аллергию. Осторожность.", pl: "Składnik zapachowy o zapachu wanilii/siana. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Może powodować alergie kontaktowe. Ostrożność.", nl: "Geurbestanddeel met vanille-/hooigeur. Een van de 26 geurallergenen met verplichte etikettering in de EU. Kan contactallergieën veroorzaken. Voorzichtigheid." },
  },
  "citral": {
    name: { de: "Citral", ru: "Цитраль", pl: "Cytral", nl: "Citral" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Duftstoffbestandteil mit Zitronenduft. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. Kann Kontaktallergien auslösen. Vorsicht bei empfindlichen Personen.", ru: "Компонент отдушки с запахом лимона. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Может вызывать контактную аллергию. Осторожность для чувствительных людей.", pl: "Składnik zapachowy o zapachu cytryny. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Może powodować alergie kontaktowe. Ostrożność u osób wrażliwych.", nl: "Geurbestanddeel met citroengeur. Een van de 26 geurallergenen met verplichte etikettering in de EU. Kan contactallergieën veroorzaken. Voorzichtigheid bij gevoelige personen." },
  },
  "benzyl alcohol": {
    name: { de: "Benzylalkohol", ru: "Бензиловый спирт", pl: "Alkohol benzylowy", nl: "Benzylalcohol" },
    use: { de: "Konservierungsmittel / Duftstoff", ru: "консервант / отдушка", pl: "konserwant / substancja zapachowa", nl: "conserveermiddel / parfum" },
    desc: { de: "Wird als Lösungsmittel, Konservierungsmittel und Duftstoffbestandteil verwendet. Einer der 26 Duftstoffallergene mit Kennzeichnungspflicht in der EU. Kann Kontaktallergien auslösen. Vorsicht bei empfindlichen Personen.", ru: "Используется как растворитель, консервант и компонент отдушки. Один из 26 аллергенов отдушек, обязательных к указанию в ЕС. Может вызывать контактную аллергию. Осторожность для чувствительных людей.", pl: "Stosowany jako rozpuszczalnik, konserwant i składnik zapachowy. Jeden z 26 alergenów zapachowych podlegających obowiązkowemu oznakowaniu w UE. Może powodować alergie kontaktowe. Ostrożność u osób wrażliwych.", nl: "Gebruikt als oplosmiddel, conserveermiddel en geurbestanddeel. Een van de 26 geurallergenen met verplichte etikettering in de EU. Kan contactallergieën veroorzaken. Voorzichtigheid bij gevoelige personen." },
  },
  "parfum": {
    name: { de: "Parfum (Duftstoffmischung)", ru: "Парфюмерная композиция (смесь)", pl: "Kompozycja zapachowa (mieszanina)", nl: "Parfum (geurmengsel)" },
    use: { de: "Duftstoff", ru: "отдушка", pl: "substancja zapachowa", nl: "parfum" },
    desc: { de: "Allgemeiner Begriff, der Dutzende nicht einzeln deklarierter Substanzen verbergen kann. Die EU erlaubt das Wort \"Parfum\", die 26 bekannten Allergene müssen jedoch weiterhin gesondert angegeben werden. Duftstoffe gehören zu den häufigsten Ursachen kosmetischer Allergien. Mäßigung, besonders bei empfindlicher Haut.", ru: "Общий термин, за которым могут скрываться десятки веществ, не указанных по отдельности. ЕС разрешает слово \"парфюм\", но 26 известных аллергенов всё равно должны указываться отдельно. Отдушка - одна из самых частых причин косметической аллергии. Умеренность, особенно для чувствительной кожи.", pl: "Ogólny termin, który może ukrywać dziesiątki substancji niezadeklarowanych pojedynczo. UE dopuszcza słowo \"parfum\", ale 26 znanych alergenów musi i tak być deklarowanych osobno. Substancje zapachowe to jedna z najczęstszych przyczyn alergii kosmetycznych. Umiar, zwłaszcza przy skórze wrażliwej.", nl: "Algemene term die tientallen niet afzonderlijk vermelde stoffen kan verbergen. De EU staat het woord \"parfum\" toe, maar de 26 bekende allergenen moeten toch afzonderlijk worden vermeld. Parfum is een van de meest voorkomende oorzaken van cosmetische allergieën. Matiging, vooral bij gevoelige huid." },
  },
  "bht": {
    name: { de: "BHT (Butylhydroxytoluol)", ru: "BHT (бутилгидрокситолуол)", pl: "BHT (butylohydroksytoluen)", nl: "BHT (butylhydroxytolueen)" },
    use: { de: "Antioxidans", ru: "антиоксидант", pl: "przeciwutleniacz", nl: "antioxidant" },
    desc: { de: "Antioxidans, das das Ranzigwerden verhindert. In der EU zugelassen und bei den üblichen Konzentrationen als sicher eingestuft, jedoch gibt es Diskussionen über mögliche hormonelle Effekte. Kann selten Allergien auslösen. Mäßigung.", ru: "Антиоксидант, предотвращающий прогоркание. Разрешён в ЕС и считается безопасным в обычных концентрациях, но ведутся споры о возможном эндокринном воздействии. Может изредка вызывать аллергию. Умеренность.", pl: "Przeciwutleniacz zapobiegający jełczeniu. Dozwolony w UE i uznany za bezpieczny w zwykłych stężeniach, ale toczą się dyskusje o możliwym wpływie hormonalnym. Może rzadko powodować alergie. Umiar.", nl: "Antioxidant die ranzig worden voorkomt. Toegestaan in de EU en bij gebruikelijke concentraties als veilig beschouwd, maar er is discussie over mogelijke hormonale effecten. Kan zelden allergieën veroorzaken. Matiging." },
  },
  "triclocarban": {
    name: { de: "Triclocarban", ru: "Триклокарбан", pl: "Triklokarban", nl: "Triclocarban" },
    use: { de: "antibakterieller Wirkstoff", ru: "антибактериальное средство", pl: "środek antybakteryjny", nl: "antibacterieel middel" },
    desc: { de: "Antibakterieller Wirkstoff, der mit Triclosan verwandt ist. Wird mit hormoneller Störung und Umweltproblemen in Verbindung gebracht. In der EU stark eingeschränkt und in Seifen in den USA seit 2016 verboten. Vermeiden.", ru: "Антибактериальное средство, родственное триклозану. Связано с эндокринными нарушениями и проблемами для окружающей среды. Строго ограничено в ЕС и запрещено в мыле в США с 2016 года. Избегайте.", pl: "Środek antybakteryjny spokrewniony z triklosanem. Powiązany z zaburzeniami hormonalnymi i problemami środowiskowymi. Mocno ograniczony w UE i zakazany w mydłach w USA od 2016 roku. Unikaj.", nl: "Antibacterieel middel verwant aan triclosan. In verband gebracht met hormonale verstoring en milieuproblemen. In de EU sterk beperkt en in zepen in de VS sinds 2016 verboden. Vermijden." },
  },
  "glycerin": {
    name: { de: "Glycerin", ru: "Глицерин", pl: "Gliceryna", nl: "Glycerine" },
    use: { de: "Feuchtigkeitsspender", ru: "увлажнитель", pl: "substancja nawilżająca", nl: "hydraterend middel" },
    desc: { de: "Sehr verbreiteter und sicherer feuchtigkeitsspendender Inhaltsstoff. In der EU ohne Einschränkungen zugelassen. Zieht Wasser an und hält es in der Haut. Keine bekannten Risiken.", ru: "Очень распространённый и безопасный увлажняющий ингредиент. Разрешён в ЕС без ограничений. Притягивает и удерживает воду в коже. Известных рисков нет.", pl: "Bardzo rozpowszechniony i bezpieczny składnik nawilżający. Dozwolony w UE bez ograniczeń. Przyciąga i zatrzymuje wodę w skórze. Brak znanych zagrożeń.", nl: "Zeer veelvoorkomend en veilig hydraterend ingrediënt. Toegestaan in de EU zonder beperkingen. Trekt water aan en houdt het vast in de huid. Geen bekende risico's." },
  },
  "niacinamide": {
    name: { de: "Niacinamid", ru: "Ниацинамид", pl: "Niacynamid", nl: "Niacinamide" },
    use: { de: "Wirkstoff", ru: "активный ингредиент", pl: "składnik aktywny", nl: "actief ingrediënt" },
    desc: { de: "Eine Form von Vitamin B3, ein für die Haut geschätzter Wirkstoff. In der EU zugelassen und als sicher eingestuft. Gut verträglich, mit positiven Wirkungen. Keine bekannten Risiken.", ru: "Форма витамина B3, активный ингредиент, ценимый для кожи. Разрешён в ЕС и считается безопасным. Хорошо переносится, обладает полезными эффектами. Известных рисков нет.", pl: "Forma witaminy B3, składnik aktywny ceniony dla skóry. Dozwolony w UE i uznany za bezpieczny. Dobrze tolerowany, o korzystnym działaniu. Brak znanych zagrożeń.", nl: "Een vorm van vitamine B3, een gewaardeerd actief ingrediënt voor de huid. Toegestaan in de EU en als veilig beschouwd. Goed verdragen, met gunstige effecten. Geen bekende risico's." },
  },
};
